//go:build ignore

// medal_category_gen.go — générateur de medal_category_table.go.
//
// Extrait la table `medal_id → {catégorie, super-section, sort}` depuis le fichier
// SpartanRecord AllMedals.tsx (source de vérité de la taxonomie Halo Infinite des
// médailles). On ne récupère QUE `category` (MedalType.X) et `sort` ; les
// noms/descriptions/rareté/images restent servis par LevelUp (medal_definitions).
//
// PROCÉDURE DE RAFRAÎCHISSEMENT (quand AllMedals.tsx / MedalType évoluent) :
//
//	cd apps/go-api/internal/games/halo_infinite
//	go run medal_category_gen.go \
//	    -src="<chemin>/SpartanRecord/src/Objects/Helpers/AllMedals.tsx" \
//	    -out=medal_category_table.go
//
// Puis `gofmt -w medal_category_table.go` et commit. Le rollup catégorie(23)→
// super-section(4) et l'énumération MedalType sont figés dans memberToCategory
// ci-dessous (source : SpartanRecord src/Objects/Pieces/Medal.tsx +
// src/Assets/Components/Medals/MedalTypeBreakdown.tsx). Un MedalType inconnu dans
// AllMedals.tsx fait ÉCHOUER la génération (signal d'un rollup à compléter).
package main

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// memberToCategory mappe un membre de l'enum MedalType (tel qu'écrit après
// `MedalType.` dans AllMedals.tsx) vers {clé de catégorie stable, super-section}.
// 23 catégories → 4 super-sections (classics, game_modes, weapons_equipment, other).
var memberToCategory = map[string][2]string{
	"Spree":         {"spree", "classics"},
	"MultiKill":     {"multikill", "classics"},
	"Assists":       {"assists", "other"},
	"Boom":          {"boom", "weapons_equipment"},
	"Equipment":     {"equipment", "weapons_equipment"},
	"GameEnd":       {"game_end", "other"},
	"Melee":         {"melee", "weapons_equipment"},
	"Skill":         {"skill", "other"},
	"Sniper":        {"sniper", "weapons_equipment"},
	"Weapons":       {"weapons", "weapons_equipment"},
	"Vehicles":      {"vehicles", "weapons_equipment"},
	"Assault":       {"assault", "game_modes"},
	"CTF":           {"ctf", "game_modes"},
	"Infection":     {"infection", "game_modes"},
	"Elimination":   {"elimination", "game_modes"},
	"Extraction":    {"extraction", "game_modes"},
	"Juggernaut":    {"juggernaut", "game_modes"},
	"KingOfTheHill": {"king_of_the_hill", "game_modes"},
	"Oddball":       {"oddball", "game_modes"},
	"Stockpile":     {"stockpile", "game_modes"},
	"VIP":           {"vip", "game_modes"},
	"Zone":          {"zone", "game_modes"},
	"Unknown":       {"other", "other"},
}

// Parsing par chunk d'entrée : `sort` est OPTIONNEL dans AllMedals.tsx (le
// constructeur Medal le défaute à -1). On délimite chaque médaille par son entête
// `<id>: {`, puis on extrait category (obligatoire) et sort (optionnel) dans le chunk.
var (
	entryStartRE = regexp.MustCompile(`(?m)^\s*(\d+):\s*\{`)
	categoryRE   = regexp.MustCompile(`category:\s*MedalType\.(\w+)`)
	sortRE       = regexp.MustCompile(`sort:\s*(-?\d+)`)
)

type genEntry struct {
	id       int64
	category string
	super    string
	sort     int
}

func main() {
	src := flagValue("-src", "")
	out := flagValue("-out", "medal_category_table.go")
	if src == "" {
		fatal("usage: go run medal_category_gen.go -src=<AllMedals.tsx> [-out=medal_category_table.go]")
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		fatal("lecture %s: %v", src, err)
	}

	content := string(raw)
	starts := entryStartRE.FindAllStringSubmatchIndex(content, -1)
	if len(starts) < 100 || len(starts) > 250 {
		fatal("nombre d'entrées anormal (%d) — attendu ~164 ; regex ou source cassées ?", len(starts))
	}

	entries := make([]genEntry, 0, len(starts))
	var unknown []string
	for i, loc := range starts {
		idStr := content[loc[2]:loc[3]]
		id, perr := strconv.ParseInt(idStr, 10, 64)
		if perr != nil {
			fatal("id non parsable %q: %v", idStr, perr)
		}
		end := len(content)
		if i+1 < len(starts) {
			end = starts[i+1][0]
		}
		chunk := content[loc[1]:end]
		catM := categoryRE.FindStringSubmatch(chunk)
		if catM == nil {
			fatal("médaille %d sans category dans AllMedals.tsx", id)
		}
		cat, ok := memberToCategory[catM[1]]
		if !ok {
			unknown = append(unknown, catM[1])
			continue
		}
		srt := -1 // défaut Medal(): sort absent → -1
		if sm := sortRE.FindStringSubmatch(chunk); sm != nil {
			srt, _ = strconv.Atoi(sm[1])
		}
		entries = append(entries, genEntry{id: id, category: cat[0], super: cat[1], sort: srt})
	}
	if len(unknown) > 0 {
		fatal("MedalType inconnu(s) dans AllMedals.tsx (compléter memberToCategory) : %s",
			strings.Join(unique(unknown), ", "))
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].id < entries[j].id })

	var b strings.Builder
	b.WriteString("// Code generated by medal_category_gen.go; DO NOT EDIT.\n")
	b.WriteString("// Source : SpartanRecord src/Objects/Helpers/AllMedals.tsx (catégorie + sort).\n")
	b.WriteString("// Rafraîchir : voir medal_category_gen.go (procédure en tête de fichier).\n\n")
	b.WriteString("package halo_infinite\n\n")
	fmt.Fprintf(&b, "// medalCategoryTable : %d médailles Halo Infinite → {catégorie, super-section, sort}.\n", len(entries))
	b.WriteString("var medalCategoryTable = map[int64]medalCategoryEntry{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%d: {%q, %q, %d},\n", e.id, e.category, e.super, e.sort)
	}
	b.WriteString("}\n")

	// gofmt la sortie AVANT écriture : garantit un fichier généré gofmt-clean ET une
	// régénération idempotente (sans quoi un futur `go generate` réémettrait du non
	// formaté → drift + hook pre-commit rouge).
	formatted, ferr := format.Source([]byte(b.String()))
	if ferr != nil {
		fatal("gofmt de la sortie générée: %v", ferr)
	}
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		fatal("écriture %s: %v", out, err)
	}
	fmt.Fprintf(os.Stderr, "medal_category_table.go généré : %d entrées → %s\n", len(entries), out)
}

// flagValue lit -name=valeur ou -name valeur depuis os.Args (évite le package flag
// pour rester trivial dans un fichier go:build ignore).
func flagValue(name, def string) string {
	for i, a := range os.Args {
		if strings.HasPrefix(a, name+"=") {
			return strings.TrimPrefix(a, name+"=")
		}
		if a == name && i+1 < len(os.Args) {
			return os.Args[i+1]
		}
	}
	return def
}

func unique(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
