/**
 * squadFocusStrings — libellés FR/EN du bandeau « Cap d'escouade » et de son
 * panneau d'objectifs. Extrait de SquadFocusStrip.tsx pour le seuil 500 L
 * (CLAUDE.md règle 5) et pour être partagé avec SquadObjectivesPanel.
 *
 * Parité FR/EN garantie par typage : `SquadFocusText` = forme du bloc `fr`, et
 * `en` doit s'y conformer.
 */
export const SQUAD_FOCUS_STRINGS = {
  fr: {
    title: "Cap d'escouade",
    saved: (name: string) => `Escouade « ${name} »`,
    objectives: (n: number) => `${n} objectif${n > 1 ? 's' : ''}`,
    manage: 'Gérer',
    hide: 'Masquer',
    saveCta: 'Enregistrer cette compo comme escouade',
    saving: 'Enregistrement…',
    saveSuccess: 'Escouade enregistrée',
    saveError: "Échec de l'enregistrement",
    renameCta: 'Renommer',
    deleteCta: 'Supprimer',
    confirmDelete: 'Confirmer ?',
    ok: 'OK',
    renamed: 'Escouade renommée',
    deleted: 'Escouade supprimée',
    noObjectives: 'Aucun objectif actif pour cette escouade.',
    join: 'Rejoindre',
    joined: 'Rejoint',
    joinedToast: 'Défi rejoint',
    joinError: 'Impossible de rejoindre le défi',
    evaluate: 'Réévaluer',
    evaluated: 'Progression recalculée',
    evalError: 'Échec du recalcul',
    created: 'Défi créé',
    createError: 'Échec de la création du défi',
    challengeDeleted: 'Défi supprimé',
    challengeDeleteError: 'Échec de la suppression du défi',
    reached: 'Atteint',
    expired: 'Expiré',
    target: (n: number) => `Cible ${n} / membre`,
    matchesN: (n: number) => `${n} match${n > 1 ? 's' : ''}`,
    challenge: 'Défi',
    propose: 'Proposer des défis',
    proposing: 'Génération…',
    create: 'Créer',
    creating: 'Création…',
    poolEmpty: 'Aucun défi proposé.',
    poolCaption:
      'Défi collectif : chaque membre cumule la métrique jusqu’à la cible, sur les matchs de l’escouade postérieurs à la création.',
    poolError: 'Échec de la génération des défis',
    orientation: (axis: string) => `Axe à renforcer : ${axis}`,
    axisLabels: {
      combat: 'Combat',
      survival: 'Survie',
      support: 'Support',
      score: 'Score',
      objective: 'Objectif',
      impact: 'Impact',
    },
  },
  en: {
    title: 'Squad focus',
    saved: (name: string) => `Squad “${name}”`,
    objectives: (n: number) => `${n} objective${n > 1 ? 's' : ''}`,
    manage: 'Manage',
    hide: 'Hide',
    saveCta: 'Save this lineup as a squad',
    saving: 'Saving…',
    saveSuccess: 'Squad saved',
    saveError: 'Save failed',
    renameCta: 'Rename',
    deleteCta: 'Delete',
    confirmDelete: 'Confirm?',
    ok: 'OK',
    renamed: 'Squad renamed',
    deleted: 'Squad deleted',
    noObjectives: 'No active objective for this squad.',
    join: 'Join',
    joined: 'Joined',
    joinedToast: 'Challenge joined',
    joinError: 'Could not join the challenge',
    evaluate: 'Re-evaluate',
    evaluated: 'Progress recalculated',
    evalError: 'Recalculation failed',
    created: 'Challenge created',
    createError: 'Failed to create challenge',
    challengeDeleted: 'Challenge deleted',
    challengeDeleteError: 'Failed to delete challenge',
    reached: 'Reached',
    expired: 'Expired',
    target: (n: number) => `Target ${n} / member`,
    matchesN: (n: number) => `${n} match${n > 1 ? 'es' : ''}`,
    challenge: 'Challenge',
    propose: 'Suggest challenges',
    proposing: 'Generating…',
    create: 'Create',
    creating: 'Creating…',
    poolEmpty: 'No challenge suggested.',
    poolCaption:
      'Team challenge: each member accumulates the metric toward the target, over squad matches after creation.',
    poolError: 'Failed to generate challenges',
    orientation: (axis: string) => `Focus to improve: ${axis}`,
    axisLabels: {
      combat: 'Combat',
      survival: 'Survival',
      support: 'Support',
      score: 'Score',
      objective: 'Objective',
      impact: 'Impact',
    },
  },
}

/** Forme d'un bloc de libellés (le bloc `fr` fait foi ; `en` s'y conforme). */
export type SquadFocusText = (typeof SQUAD_FOCUS_STRINGS)['fr']
