/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as OnboardingOpenspartanRouteImport } from './routes/onboarding.openspartan'
import { Route as LabChartsRouteImport } from './routes/lab/charts'
import { Route as AdminTitlesRouteImport } from './routes/admin/titles'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSyncRouteImport } from './routes/admin/sync'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLabRouteImport } from './routes/admin/lab'
import { Route as AdminDataQualityRouteImport } from './routes/admin/data-quality'
import { Route as AdminConvergenceRouteImport } from './routes/admin/convergence'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as PlayersPlayerSlugSynthesisRouteImport } from './routes/players/$playerSlug/synthesis'
import { Route as PlayersPlayerSlugSquadRouteImport } from './routes/players/$playerSlug/squad'
import { Route as PlayersPlayerSlugNotificationsRouteImport } from './routes/players/$playerSlug/notifications'
import { Route as PlayersPlayerSlugMediaRouteImport } from './routes/players/$playerSlug/media'
import { Route as PlayersPlayerSlugHomeRouteImport } from './routes/players/$playerSlug/home'
import { Route as PlayersPlayerSlugCompareRouteImport } from './routes/players/$playerSlug/compare'
import { Route as PlayersPlayerSlugCommendationsRouteImport } from './routes/players/$playerSlug/commendations'
import { Route as PlayersPlayerSlugCitationsRouteImport } from './routes/players/$playerSlug/citations'
import { Route as PlayersPlayerSlugCareerRouteImport } from './routes/players/$playerSlug/career_'
import { Route as PlayersPlayerSlugAscensionRouteImport } from './routes/players/$playerSlug/ascension'
import { Route as PlayersPlayerSlugStatsIndexRouteImport } from './routes/players/$playerSlug/stats/index'
import { Route as PlayersPlayerSlugSquadIndexRouteImport } from './routes/players/$playerSlug/squad/index'
import { Route as PlayersPlayerSlugPalmaresIndexRouteImport } from './routes/players/$playerSlug/palmares/index'
import { Route as PlayersPlayerSlugObjectifsIndexRouteImport } from './routes/players/$playerSlug/objectifs/index'
import { Route as PlayersPlayerSlugExplorerIndexRouteImport } from './routes/players/$playerSlug/explorer/index'
import { Route as PlayersPlayerSlugCommunityIndexRouteImport } from './routes/players/$playerSlug/community/index'
import { Route as PlayersPlayerSlugAscensionIndexRouteImport } from './routes/players/$playerSlug/ascension/index'
import { Route as PlayersPlayerSlugStatsTimeseriesRouteImport } from './routes/players/$playerSlug/stats/timeseries'
import { Route as PlayersPlayerSlugStatsSynthesisRouteImport } from './routes/players/$playerSlug/stats/synthesis'
import { Route as PlayersPlayerSlugStatsSessionsRouteImport } from './routes/players/$playerSlug/stats/sessions'
import { Route as PlayersPlayerSlugSquadSynergiesRouteImport } from './routes/players/$playerSlug/squad/synergies'
import { Route as PlayersPlayerSlugSquadContributionsRouteImport } from './routes/players/$playerSlug/squad/contributions'
import { Route as PlayersPlayerSlugPalmaresRelationsRouteImport } from './routes/players/$playerSlug/palmares/relations'
import { Route as PlayersPlayerSlugPalmaresPrestigeRouteImport } from './routes/players/$playerSlug/palmares/prestige'
import { Route as PlayersPlayerSlugMatchesMatchIdRouteImport } from './routes/players/$playerSlug/matches/$matchId'
import { Route as PlayersPlayerSlugCommunityRelationsRouteImport } from './routes/players/$playerSlug/community/relations'
import { Route as PlayersPlayerSlugCommunityPrestigeRouteImport } from './routes/players/$playerSlug/community/prestige'
import { Route as PlayersPlayerSlugCommunityCompareRouteImport } from './routes/players/$playerSlug/community/compare'
import { Route as PlayersPlayerSlugCareerSeasonPassRouteImport } from './routes/players/$playerSlug/career/season-pass'
import { Route as PlayersPlayerSlugCareerCommendationsRouteImport } from './routes/players/$playerSlug/career/commendations'
import { Route as PlayersPlayerSlugCareerCitationsRouteImport } from './routes/players/$playerSlug/career/citations'
import { Route as PlayersPlayerSlugAscensionRealisationsRouteImport } from './routes/players/$playerSlug/ascension/realisations'
import { Route as PlayersPlayerSlugAscensionCoachingRouteImport } from './routes/players/$playerSlug/ascension/coaching'
import { Route as PlayersPlayerSlugMatchesMatchIdReplayRouteImport } from './routes/players/$playerSlug/matches/$matchId/replay'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOpenspartanRoute = OnboardingOpenspartanRouteImport.update({
  id: '/onboarding/openspartan',
  path: '/onboarding/openspartan',
  getParentRoute: () => rootRouteImport,
} as any)
const LabChartsRoute = LabChartsRouteImport.update({
  id: '/lab/charts',
  path: '/lab/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTitlesRoute = AdminTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabRoute = AdminLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataQualityRoute = AdminDataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConvergenceRoute = AdminConvergenceRouteImport.update({
  id: '/convergence',
  path: '/convergence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const PlayersPlayerSlugSynthesisRoute =
  PlayersPlayerSlugSynthesisRouteImport.update({
    id: '/synthesis',
    path: '/synthesis',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugSquadRoute = PlayersPlayerSlugSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugNotificationsRoute =
  PlayersPlayerSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugMediaRoute = PlayersPlayerSlugMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugHomeRoute = PlayersPlayerSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugCompareRoute =
  PlayersPlayerSlugCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCommendationsRoute =
  PlayersPlayerSlugCommendationsRouteImport.update({
    id: '/commendations',
    path: '/commendations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCitationsRoute =
  PlayersPlayerSlugCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCareerRoute = PlayersPlayerSlugCareerRouteImport.update({
  id: '/career_',
  path: '/career',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugAscensionRoute =
  PlayersPlayerSlugAscensionRouteImport.update({
    id: '/ascension',
    path: '/ascension',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsIndexRoute =
  PlayersPlayerSlugStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugSquadIndexRoute =
  PlayersPlayerSlugSquadIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlayersPlayerSlugSquadRoute,
  } as any)
const PlayersPlayerSlugPalmaresIndexRoute =
  PlayersPlayerSlugPalmaresIndexRouteImport.update({
    id: '/palmares/',
    path: '/palmares/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugObjectifsIndexRoute =
  PlayersPlayerSlugObjectifsIndexRouteImport.update({
    id: '/objectifs/',
    path: '/objectifs/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugExplorerIndexRoute =
  PlayersPlayerSlugExplorerIndexRouteImport.update({
    id: '/explorer/',
    path: '/explorer/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCommunityIndexRoute =
  PlayersPlayerSlugCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugAscensionIndexRoute =
  PlayersPlayerSlugAscensionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlayersPlayerSlugAscensionRoute,
  } as any)
const PlayersPlayerSlugStatsTimeseriesRoute =
  PlayersPlayerSlugStatsTimeseriesRouteImport.update({
    id: '/stats/timeseries',
    path: '/stats/timeseries',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsSynthesisRoute =
  PlayersPlayerSlugStatsSynthesisRouteImport.update({
    id: '/stats/synthesis',
    path: '/stats/synthesis',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsSessionsRoute =
  PlayersPlayerSlugStatsSessionsRouteImport.update({
    id: '/stats/sessions',
    path: '/stats/sessions',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugSquadSynergiesRoute =
  PlayersPlayerSlugSquadSynergiesRouteImport.update({
    id: '/synergies',
    path: '/synergies',
    getParentRoute: () => PlayersPlayerSlugSquadRoute,
  } as any)
const PlayersPlayerSlugSquadContributionsRoute =
  PlayersPlayerSlugSquadContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => PlayersPlayerSlugSquadRoute,
  } as any)
const PlayersPlayerSlugPalmaresRelationsRoute =
  PlayersPlayerSlugPalmaresRelationsRouteImport.update({
    id: '/palmares/relations',
    path: '/palmares/relations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugPalmaresPrestigeRoute =
  PlayersPlayerSlugPalmaresPrestigeRouteImport.update({
    id: '/palmares/prestige',
    path: '/palmares/prestige',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugMatchesMatchIdRoute =
  PlayersPlayerSlugMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCommunityRelationsRoute =
  PlayersPlayerSlugCommunityRelationsRouteImport.update({
    id: '/community/relations',
    path: '/community/relations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCommunityPrestigeRoute =
  PlayersPlayerSlugCommunityPrestigeRouteImport.update({
    id: '/community/prestige',
    path: '/community/prestige',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCommunityCompareRoute =
  PlayersPlayerSlugCommunityCompareRouteImport.update({
    id: '/community/compare',
    path: '/community/compare',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCareerSeasonPassRoute =
  PlayersPlayerSlugCareerSeasonPassRouteImport.update({
    id: '/career/season-pass',
    path: '/career/season-pass',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCareerCommendationsRoute =
  PlayersPlayerSlugCareerCommendationsRouteImport.update({
    id: '/career/commendations',
    path: '/career/commendations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugCareerCitationsRoute =
  PlayersPlayerSlugCareerCitationsRouteImport.update({
    id: '/career/citations',
    path: '/career/citations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugAscensionRealisationsRoute =
  PlayersPlayerSlugAscensionRealisationsRouteImport.update({
    id: '/realisations',
    path: '/realisations',
    getParentRoute: () => PlayersPlayerSlugAscensionRoute,
  } as any)
const PlayersPlayerSlugAscensionCoachingRoute =
  PlayersPlayerSlugAscensionCoachingRouteImport.update({
    id: '/coaching',
    path: '/coaching',
    getParentRoute: () => PlayersPlayerSlugAscensionRoute,
  } as any)
const PlayersPlayerSlugMatchesMatchIdReplayRoute =
  PlayersPlayerSlugMatchesMatchIdReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => PlayersPlayerSlugMatchesMatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/groups': typeof GroupsRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/convergence': typeof AdminConvergenceRoute
  '/admin/data-quality': typeof AdminDataQualityRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/titles': typeof AdminTitlesRoute
  '/lab/charts': typeof LabChartsRoute
  '/onboarding/openspartan': typeof OnboardingOpenspartanRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/players/$playerSlug/ascension': typeof PlayersPlayerSlugAscensionRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/citations': typeof PlayersPlayerSlugCitationsRoute
  '/players/$playerSlug/commendations': typeof PlayersPlayerSlugCommendationsRoute
  '/players/$playerSlug/compare': typeof PlayersPlayerSlugCompareRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/notifications': typeof PlayersPlayerSlugNotificationsRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRouteWithChildren
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/ascension/coaching': typeof PlayersPlayerSlugAscensionCoachingRoute
  '/players/$playerSlug/ascension/realisations': typeof PlayersPlayerSlugAscensionRealisationsRoute
  '/players/$playerSlug/career/citations': typeof PlayersPlayerSlugCareerCitationsRoute
  '/players/$playerSlug/career/commendations': typeof PlayersPlayerSlugCareerCommendationsRoute
  '/players/$playerSlug/career/season-pass': typeof PlayersPlayerSlugCareerSeasonPassRoute
  '/players/$playerSlug/community/compare': typeof PlayersPlayerSlugCommunityCompareRoute
  '/players/$playerSlug/community/prestige': typeof PlayersPlayerSlugCommunityPrestigeRoute
  '/players/$playerSlug/community/relations': typeof PlayersPlayerSlugCommunityRelationsRoute
  '/players/$playerSlug/matches/$matchId': typeof PlayersPlayerSlugMatchesMatchIdRouteWithChildren
  '/players/$playerSlug/palmares/prestige': typeof PlayersPlayerSlugPalmaresPrestigeRoute
  '/players/$playerSlug/palmares/relations': typeof PlayersPlayerSlugPalmaresRelationsRoute
  '/players/$playerSlug/squad/contributions': typeof PlayersPlayerSlugSquadContributionsRoute
  '/players/$playerSlug/squad/synergies': typeof PlayersPlayerSlugSquadSynergiesRoute
  '/players/$playerSlug/stats/sessions': typeof PlayersPlayerSlugStatsSessionsRoute
  '/players/$playerSlug/stats/synthesis': typeof PlayersPlayerSlugStatsSynthesisRoute
  '/players/$playerSlug/stats/timeseries': typeof PlayersPlayerSlugStatsTimeseriesRoute
  '/players/$playerSlug/ascension/': typeof PlayersPlayerSlugAscensionIndexRoute
  '/players/$playerSlug/community/': typeof PlayersPlayerSlugCommunityIndexRoute
  '/players/$playerSlug/explorer/': typeof PlayersPlayerSlugExplorerIndexRoute
  '/players/$playerSlug/objectifs/': typeof PlayersPlayerSlugObjectifsIndexRoute
  '/players/$playerSlug/palmares/': typeof PlayersPlayerSlugPalmaresIndexRoute
  '/players/$playerSlug/squad/': typeof PlayersPlayerSlugSquadIndexRoute
  '/players/$playerSlug/stats/': typeof PlayersPlayerSlugStatsIndexRoute
  '/players/$playerSlug/matches/$matchId/replay': typeof PlayersPlayerSlugMatchesMatchIdReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/groups': typeof GroupsRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/convergence': typeof AdminConvergenceRoute
  '/admin/data-quality': typeof AdminDataQualityRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/titles': typeof AdminTitlesRoute
  '/lab/charts': typeof LabChartsRoute
  '/onboarding/openspartan': typeof OnboardingOpenspartanRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/citations': typeof PlayersPlayerSlugCitationsRoute
  '/players/$playerSlug/commendations': typeof PlayersPlayerSlugCommendationsRoute
  '/players/$playerSlug/compare': typeof PlayersPlayerSlugCompareRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/notifications': typeof PlayersPlayerSlugNotificationsRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/ascension/coaching': typeof PlayersPlayerSlugAscensionCoachingRoute
  '/players/$playerSlug/ascension/realisations': typeof PlayersPlayerSlugAscensionRealisationsRoute
  '/players/$playerSlug/career/citations': typeof PlayersPlayerSlugCareerCitationsRoute
  '/players/$playerSlug/career/commendations': typeof PlayersPlayerSlugCareerCommendationsRoute
  '/players/$playerSlug/career/season-pass': typeof PlayersPlayerSlugCareerSeasonPassRoute
  '/players/$playerSlug/community/compare': typeof PlayersPlayerSlugCommunityCompareRoute
  '/players/$playerSlug/community/prestige': typeof PlayersPlayerSlugCommunityPrestigeRoute
  '/players/$playerSlug/community/relations': typeof PlayersPlayerSlugCommunityRelationsRoute
  '/players/$playerSlug/matches/$matchId': typeof PlayersPlayerSlugMatchesMatchIdRouteWithChildren
  '/players/$playerSlug/palmares/prestige': typeof PlayersPlayerSlugPalmaresPrestigeRoute
  '/players/$playerSlug/palmares/relations': typeof PlayersPlayerSlugPalmaresRelationsRoute
  '/players/$playerSlug/squad/contributions': typeof PlayersPlayerSlugSquadContributionsRoute
  '/players/$playerSlug/squad/synergies': typeof PlayersPlayerSlugSquadSynergiesRoute
  '/players/$playerSlug/stats/sessions': typeof PlayersPlayerSlugStatsSessionsRoute
  '/players/$playerSlug/stats/synthesis': typeof PlayersPlayerSlugStatsSynthesisRoute
  '/players/$playerSlug/stats/timeseries': typeof PlayersPlayerSlugStatsTimeseriesRoute
  '/players/$playerSlug/ascension': typeof PlayersPlayerSlugAscensionIndexRoute
  '/players/$playerSlug/community': typeof PlayersPlayerSlugCommunityIndexRoute
  '/players/$playerSlug/explorer': typeof PlayersPlayerSlugExplorerIndexRoute
  '/players/$playerSlug/objectifs': typeof PlayersPlayerSlugObjectifsIndexRoute
  '/players/$playerSlug/palmares': typeof PlayersPlayerSlugPalmaresIndexRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadIndexRoute
  '/players/$playerSlug/stats': typeof PlayersPlayerSlugStatsIndexRoute
  '/players/$playerSlug/matches/$matchId/replay': typeof PlayersPlayerSlugMatchesMatchIdReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/groups': typeof GroupsRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/convergence': typeof AdminConvergenceRoute
  '/admin/data-quality': typeof AdminDataQualityRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/titles': typeof AdminTitlesRoute
  '/lab/charts': typeof LabChartsRoute
  '/onboarding/openspartan': typeof OnboardingOpenspartanRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/players/$playerSlug/ascension': typeof PlayersPlayerSlugAscensionRouteWithChildren
  '/players/$playerSlug/career_': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/citations': typeof PlayersPlayerSlugCitationsRoute
  '/players/$playerSlug/commendations': typeof PlayersPlayerSlugCommendationsRoute
  '/players/$playerSlug/compare': typeof PlayersPlayerSlugCompareRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/notifications': typeof PlayersPlayerSlugNotificationsRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRouteWithChildren
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/ascension/coaching': typeof PlayersPlayerSlugAscensionCoachingRoute
  '/players/$playerSlug/ascension/realisations': typeof PlayersPlayerSlugAscensionRealisationsRoute
  '/players/$playerSlug/career/citations': typeof PlayersPlayerSlugCareerCitationsRoute
  '/players/$playerSlug/career/commendations': typeof PlayersPlayerSlugCareerCommendationsRoute
  '/players/$playerSlug/career/season-pass': typeof PlayersPlayerSlugCareerSeasonPassRoute
  '/players/$playerSlug/community/compare': typeof PlayersPlayerSlugCommunityCompareRoute
  '/players/$playerSlug/community/prestige': typeof PlayersPlayerSlugCommunityPrestigeRoute
  '/players/$playerSlug/community/relations': typeof PlayersPlayerSlugCommunityRelationsRoute
  '/players/$playerSlug/matches/$matchId': typeof PlayersPlayerSlugMatchesMatchIdRouteWithChildren
  '/players/$playerSlug/palmares/prestige': typeof PlayersPlayerSlugPalmaresPrestigeRoute
  '/players/$playerSlug/palmares/relations': typeof PlayersPlayerSlugPalmaresRelationsRoute
  '/players/$playerSlug/squad/contributions': typeof PlayersPlayerSlugSquadContributionsRoute
  '/players/$playerSlug/squad/synergies': typeof PlayersPlayerSlugSquadSynergiesRoute
  '/players/$playerSlug/stats/sessions': typeof PlayersPlayerSlugStatsSessionsRoute
  '/players/$playerSlug/stats/synthesis': typeof PlayersPlayerSlugStatsSynthesisRoute
  '/players/$playerSlug/stats/timeseries': typeof PlayersPlayerSlugStatsTimeseriesRoute
  '/players/$playerSlug/ascension/': typeof PlayersPlayerSlugAscensionIndexRoute
  '/players/$playerSlug/community/': typeof PlayersPlayerSlugCommunityIndexRoute
  '/players/$playerSlug/explorer/': typeof PlayersPlayerSlugExplorerIndexRoute
  '/players/$playerSlug/objectifs/': typeof PlayersPlayerSlugObjectifsIndexRoute
  '/players/$playerSlug/palmares/': typeof PlayersPlayerSlugPalmaresIndexRoute
  '/players/$playerSlug/squad/': typeof PlayersPlayerSlugSquadIndexRoute
  '/players/$playerSlug/stats/': typeof PlayersPlayerSlugStatsIndexRoute
  '/players/$playerSlug/matches/$matchId/replay': typeof PlayersPlayerSlugMatchesMatchIdReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/groups'
    | '/help'
    | '/join'
    | '/login'
    | '/register'
    | '/settings'
    | '/setup'
    | '/admin/access'
    | '/admin/convergence'
    | '/admin/data-quality'
    | '/admin/lab'
    | '/admin/logs'
    | '/admin/sync'
    | '/admin/system'
    | '/admin/titles'
    | '/lab/charts'
    | '/onboarding/openspartan'
    | '/players/$playerSlug'
    | '/admin/'
    | '/players/$playerSlug/ascension'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/citations'
    | '/players/$playerSlug/commendations'
    | '/players/$playerSlug/compare'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/notifications'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/ascension/coaching'
    | '/players/$playerSlug/ascension/realisations'
    | '/players/$playerSlug/career/citations'
    | '/players/$playerSlug/career/commendations'
    | '/players/$playerSlug/career/season-pass'
    | '/players/$playerSlug/community/compare'
    | '/players/$playerSlug/community/prestige'
    | '/players/$playerSlug/community/relations'
    | '/players/$playerSlug/matches/$matchId'
    | '/players/$playerSlug/palmares/prestige'
    | '/players/$playerSlug/palmares/relations'
    | '/players/$playerSlug/squad/contributions'
    | '/players/$playerSlug/squad/synergies'
    | '/players/$playerSlug/stats/sessions'
    | '/players/$playerSlug/stats/synthesis'
    | '/players/$playerSlug/stats/timeseries'
    | '/players/$playerSlug/ascension/'
    | '/players/$playerSlug/community/'
    | '/players/$playerSlug/explorer/'
    | '/players/$playerSlug/objectifs/'
    | '/players/$playerSlug/palmares/'
    | '/players/$playerSlug/squad/'
    | '/players/$playerSlug/stats/'
    | '/players/$playerSlug/matches/$matchId/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/groups'
    | '/help'
    | '/join'
    | '/login'
    | '/register'
    | '/settings'
    | '/setup'
    | '/admin/access'
    | '/admin/convergence'
    | '/admin/data-quality'
    | '/admin/lab'
    | '/admin/logs'
    | '/admin/sync'
    | '/admin/system'
    | '/admin/titles'
    | '/lab/charts'
    | '/onboarding/openspartan'
    | '/players/$playerSlug'
    | '/admin'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/citations'
    | '/players/$playerSlug/commendations'
    | '/players/$playerSlug/compare'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/notifications'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/ascension/coaching'
    | '/players/$playerSlug/ascension/realisations'
    | '/players/$playerSlug/career/citations'
    | '/players/$playerSlug/career/commendations'
    | '/players/$playerSlug/career/season-pass'
    | '/players/$playerSlug/community/compare'
    | '/players/$playerSlug/community/prestige'
    | '/players/$playerSlug/community/relations'
    | '/players/$playerSlug/matches/$matchId'
    | '/players/$playerSlug/palmares/prestige'
    | '/players/$playerSlug/palmares/relations'
    | '/players/$playerSlug/squad/contributions'
    | '/players/$playerSlug/squad/synergies'
    | '/players/$playerSlug/stats/sessions'
    | '/players/$playerSlug/stats/synthesis'
    | '/players/$playerSlug/stats/timeseries'
    | '/players/$playerSlug/ascension'
    | '/players/$playerSlug/community'
    | '/players/$playerSlug/explorer'
    | '/players/$playerSlug/objectifs'
    | '/players/$playerSlug/palmares'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/stats'
    | '/players/$playerSlug/matches/$matchId/replay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/groups'
    | '/help'
    | '/join'
    | '/login'
    | '/register'
    | '/settings'
    | '/setup'
    | '/admin/access'
    | '/admin/convergence'
    | '/admin/data-quality'
    | '/admin/lab'
    | '/admin/logs'
    | '/admin/sync'
    | '/admin/system'
    | '/admin/titles'
    | '/lab/charts'
    | '/onboarding/openspartan'
    | '/players/$playerSlug'
    | '/admin/'
    | '/players/$playerSlug/ascension'
    | '/players/$playerSlug/career_'
    | '/players/$playerSlug/citations'
    | '/players/$playerSlug/commendations'
    | '/players/$playerSlug/compare'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/notifications'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/ascension/coaching'
    | '/players/$playerSlug/ascension/realisations'
    | '/players/$playerSlug/career/citations'
    | '/players/$playerSlug/career/commendations'
    | '/players/$playerSlug/career/season-pass'
    | '/players/$playerSlug/community/compare'
    | '/players/$playerSlug/community/prestige'
    | '/players/$playerSlug/community/relations'
    | '/players/$playerSlug/matches/$matchId'
    | '/players/$playerSlug/palmares/prestige'
    | '/players/$playerSlug/palmares/relations'
    | '/players/$playerSlug/squad/contributions'
    | '/players/$playerSlug/squad/synergies'
    | '/players/$playerSlug/stats/sessions'
    | '/players/$playerSlug/stats/synthesis'
    | '/players/$playerSlug/stats/timeseries'
    | '/players/$playerSlug/ascension/'
    | '/players/$playerSlug/community/'
    | '/players/$playerSlug/explorer/'
    | '/players/$playerSlug/objectifs/'
    | '/players/$playerSlug/palmares/'
    | '/players/$playerSlug/squad/'
    | '/players/$playerSlug/stats/'
    | '/players/$playerSlug/matches/$matchId/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  GroupsRoute: typeof GroupsRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  LabChartsRoute: typeof LabChartsRoute
  OnboardingOpenspartanRoute: typeof OnboardingOpenspartanRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/openspartan': {
      id: '/onboarding/openspartan'
      path: '/onboarding/openspartan'
      fullPath: '/onboarding/openspartan'
      preLoaderRoute: typeof OnboardingOpenspartanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/charts': {
      id: '/lab/charts'
      path: '/lab/charts'
      fullPath: '/lab/charts'
      preLoaderRoute: typeof LabChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/titles': {
      id: '/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AdminTitlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lab': {
      id: '/admin/lab'
      path: '/lab'
      fullPath: '/admin/lab'
      preLoaderRoute: typeof AdminLabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-quality': {
      id: '/admin/data-quality'
      path: '/data-quality'
      fullPath: '/admin/data-quality'
      preLoaderRoute: typeof AdminDataQualityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/convergence': {
      id: '/admin/convergence'
      path: '/convergence'
      fullPath: '/admin/convergence'
      preLoaderRoute: typeof AdminConvergenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/players/$playerSlug/synthesis': {
      id: '/players/$playerSlug/synthesis'
      path: '/synthesis'
      fullPath: '/players/$playerSlug/synthesis'
      preLoaderRoute: typeof PlayersPlayerSlugSynthesisRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/squad': {
      id: '/players/$playerSlug/squad'
      path: '/squad'
      fullPath: '/players/$playerSlug/squad'
      preLoaderRoute: typeof PlayersPlayerSlugSquadRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/notifications': {
      id: '/players/$playerSlug/notifications'
      path: '/notifications'
      fullPath: '/players/$playerSlug/notifications'
      preLoaderRoute: typeof PlayersPlayerSlugNotificationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/media': {
      id: '/players/$playerSlug/media'
      path: '/media'
      fullPath: '/players/$playerSlug/media'
      preLoaderRoute: typeof PlayersPlayerSlugMediaRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/home': {
      id: '/players/$playerSlug/home'
      path: '/home'
      fullPath: '/players/$playerSlug/home'
      preLoaderRoute: typeof PlayersPlayerSlugHomeRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/compare': {
      id: '/players/$playerSlug/compare'
      path: '/compare'
      fullPath: '/players/$playerSlug/compare'
      preLoaderRoute: typeof PlayersPlayerSlugCompareRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/commendations': {
      id: '/players/$playerSlug/commendations'
      path: '/commendations'
      fullPath: '/players/$playerSlug/commendations'
      preLoaderRoute: typeof PlayersPlayerSlugCommendationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/citations': {
      id: '/players/$playerSlug/citations'
      path: '/citations'
      fullPath: '/players/$playerSlug/citations'
      preLoaderRoute: typeof PlayersPlayerSlugCitationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/career_': {
      id: '/players/$playerSlug/career_'
      path: '/career'
      fullPath: '/players/$playerSlug/career'
      preLoaderRoute: typeof PlayersPlayerSlugCareerRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/ascension': {
      id: '/players/$playerSlug/ascension'
      path: '/ascension'
      fullPath: '/players/$playerSlug/ascension'
      preLoaderRoute: typeof PlayersPlayerSlugAscensionRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/': {
      id: '/players/$playerSlug/stats/'
      path: '/stats'
      fullPath: '/players/$playerSlug/stats/'
      preLoaderRoute: typeof PlayersPlayerSlugStatsIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/squad/': {
      id: '/players/$playerSlug/squad/'
      path: '/'
      fullPath: '/players/$playerSlug/squad/'
      preLoaderRoute: typeof PlayersPlayerSlugSquadIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugSquadRoute
    }
    '/players/$playerSlug/palmares/': {
      id: '/players/$playerSlug/palmares/'
      path: '/palmares'
      fullPath: '/players/$playerSlug/palmares/'
      preLoaderRoute: typeof PlayersPlayerSlugPalmaresIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/objectifs/': {
      id: '/players/$playerSlug/objectifs/'
      path: '/objectifs'
      fullPath: '/players/$playerSlug/objectifs/'
      preLoaderRoute: typeof PlayersPlayerSlugObjectifsIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/explorer/': {
      id: '/players/$playerSlug/explorer/'
      path: '/explorer'
      fullPath: '/players/$playerSlug/explorer/'
      preLoaderRoute: typeof PlayersPlayerSlugExplorerIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/community/': {
      id: '/players/$playerSlug/community/'
      path: '/community'
      fullPath: '/players/$playerSlug/community/'
      preLoaderRoute: typeof PlayersPlayerSlugCommunityIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/ascension/': {
      id: '/players/$playerSlug/ascension/'
      path: '/'
      fullPath: '/players/$playerSlug/ascension/'
      preLoaderRoute: typeof PlayersPlayerSlugAscensionIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugAscensionRoute
    }
    '/players/$playerSlug/stats/timeseries': {
      id: '/players/$playerSlug/stats/timeseries'
      path: '/stats/timeseries'
      fullPath: '/players/$playerSlug/stats/timeseries'
      preLoaderRoute: typeof PlayersPlayerSlugStatsTimeseriesRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/synthesis': {
      id: '/players/$playerSlug/stats/synthesis'
      path: '/stats/synthesis'
      fullPath: '/players/$playerSlug/stats/synthesis'
      preLoaderRoute: typeof PlayersPlayerSlugStatsSynthesisRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/sessions': {
      id: '/players/$playerSlug/stats/sessions'
      path: '/stats/sessions'
      fullPath: '/players/$playerSlug/stats/sessions'
      preLoaderRoute: typeof PlayersPlayerSlugStatsSessionsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/squad/synergies': {
      id: '/players/$playerSlug/squad/synergies'
      path: '/synergies'
      fullPath: '/players/$playerSlug/squad/synergies'
      preLoaderRoute: typeof PlayersPlayerSlugSquadSynergiesRouteImport
      parentRoute: typeof PlayersPlayerSlugSquadRoute
    }
    '/players/$playerSlug/squad/contributions': {
      id: '/players/$playerSlug/squad/contributions'
      path: '/contributions'
      fullPath: '/players/$playerSlug/squad/contributions'
      preLoaderRoute: typeof PlayersPlayerSlugSquadContributionsRouteImport
      parentRoute: typeof PlayersPlayerSlugSquadRoute
    }
    '/players/$playerSlug/palmares/relations': {
      id: '/players/$playerSlug/palmares/relations'
      path: '/palmares/relations'
      fullPath: '/players/$playerSlug/palmares/relations'
      preLoaderRoute: typeof PlayersPlayerSlugPalmaresRelationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/palmares/prestige': {
      id: '/players/$playerSlug/palmares/prestige'
      path: '/palmares/prestige'
      fullPath: '/players/$playerSlug/palmares/prestige'
      preLoaderRoute: typeof PlayersPlayerSlugPalmaresPrestigeRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/matches/$matchId': {
      id: '/players/$playerSlug/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/players/$playerSlug/matches/$matchId'
      preLoaderRoute: typeof PlayersPlayerSlugMatchesMatchIdRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/community/relations': {
      id: '/players/$playerSlug/community/relations'
      path: '/community/relations'
      fullPath: '/players/$playerSlug/community/relations'
      preLoaderRoute: typeof PlayersPlayerSlugCommunityRelationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/community/prestige': {
      id: '/players/$playerSlug/community/prestige'
      path: '/community/prestige'
      fullPath: '/players/$playerSlug/community/prestige'
      preLoaderRoute: typeof PlayersPlayerSlugCommunityPrestigeRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/community/compare': {
      id: '/players/$playerSlug/community/compare'
      path: '/community/compare'
      fullPath: '/players/$playerSlug/community/compare'
      preLoaderRoute: typeof PlayersPlayerSlugCommunityCompareRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/career/season-pass': {
      id: '/players/$playerSlug/career/season-pass'
      path: '/career/season-pass'
      fullPath: '/players/$playerSlug/career/season-pass'
      preLoaderRoute: typeof PlayersPlayerSlugCareerSeasonPassRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/career/commendations': {
      id: '/players/$playerSlug/career/commendations'
      path: '/career/commendations'
      fullPath: '/players/$playerSlug/career/commendations'
      preLoaderRoute: typeof PlayersPlayerSlugCareerCommendationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/career/citations': {
      id: '/players/$playerSlug/career/citations'
      path: '/career/citations'
      fullPath: '/players/$playerSlug/career/citations'
      preLoaderRoute: typeof PlayersPlayerSlugCareerCitationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/ascension/realisations': {
      id: '/players/$playerSlug/ascension/realisations'
      path: '/realisations'
      fullPath: '/players/$playerSlug/ascension/realisations'
      preLoaderRoute: typeof PlayersPlayerSlugAscensionRealisationsRouteImport
      parentRoute: typeof PlayersPlayerSlugAscensionRoute
    }
    '/players/$playerSlug/ascension/coaching': {
      id: '/players/$playerSlug/ascension/coaching'
      path: '/coaching'
      fullPath: '/players/$playerSlug/ascension/coaching'
      preLoaderRoute: typeof PlayersPlayerSlugAscensionCoachingRouteImport
      parentRoute: typeof PlayersPlayerSlugAscensionRoute
    }
    '/players/$playerSlug/matches/$matchId/replay': {
      id: '/players/$playerSlug/matches/$matchId/replay'
      path: '/replay'
      fullPath: '/players/$playerSlug/matches/$matchId/replay'
      preLoaderRoute: typeof PlayersPlayerSlugMatchesMatchIdReplayRouteImport
      parentRoute: typeof PlayersPlayerSlugMatchesMatchIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminConvergenceRoute: typeof AdminConvergenceRoute
  AdminDataQualityRoute: typeof AdminDataQualityRoute
  AdminLabRoute: typeof AdminLabRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTitlesRoute: typeof AdminTitlesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminConvergenceRoute: AdminConvergenceRoute,
  AdminDataQualityRoute: AdminDataQualityRoute,
  AdminLabRoute: AdminLabRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTitlesRoute: AdminTitlesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PlayersPlayerSlugAscensionRouteChildren {
  PlayersPlayerSlugAscensionCoachingRoute: typeof PlayersPlayerSlugAscensionCoachingRoute
  PlayersPlayerSlugAscensionRealisationsRoute: typeof PlayersPlayerSlugAscensionRealisationsRoute
  PlayersPlayerSlugAscensionIndexRoute: typeof PlayersPlayerSlugAscensionIndexRoute
}

const PlayersPlayerSlugAscensionRouteChildren: PlayersPlayerSlugAscensionRouteChildren =
  {
    PlayersPlayerSlugAscensionCoachingRoute:
      PlayersPlayerSlugAscensionCoachingRoute,
    PlayersPlayerSlugAscensionRealisationsRoute:
      PlayersPlayerSlugAscensionRealisationsRoute,
    PlayersPlayerSlugAscensionIndexRoute: PlayersPlayerSlugAscensionIndexRoute,
  }

const PlayersPlayerSlugAscensionRouteWithChildren =
  PlayersPlayerSlugAscensionRoute._addFileChildren(
    PlayersPlayerSlugAscensionRouteChildren,
  )

interface PlayersPlayerSlugSquadRouteChildren {
  PlayersPlayerSlugSquadContributionsRoute: typeof PlayersPlayerSlugSquadContributionsRoute
  PlayersPlayerSlugSquadSynergiesRoute: typeof PlayersPlayerSlugSquadSynergiesRoute
  PlayersPlayerSlugSquadIndexRoute: typeof PlayersPlayerSlugSquadIndexRoute
}

const PlayersPlayerSlugSquadRouteChildren: PlayersPlayerSlugSquadRouteChildren =
  {
    PlayersPlayerSlugSquadContributionsRoute:
      PlayersPlayerSlugSquadContributionsRoute,
    PlayersPlayerSlugSquadSynergiesRoute: PlayersPlayerSlugSquadSynergiesRoute,
    PlayersPlayerSlugSquadIndexRoute: PlayersPlayerSlugSquadIndexRoute,
  }

const PlayersPlayerSlugSquadRouteWithChildren =
  PlayersPlayerSlugSquadRoute._addFileChildren(
    PlayersPlayerSlugSquadRouteChildren,
  )

interface PlayersPlayerSlugMatchesMatchIdRouteChildren {
  PlayersPlayerSlugMatchesMatchIdReplayRoute: typeof PlayersPlayerSlugMatchesMatchIdReplayRoute
}

const PlayersPlayerSlugMatchesMatchIdRouteChildren: PlayersPlayerSlugMatchesMatchIdRouteChildren =
  {
    PlayersPlayerSlugMatchesMatchIdReplayRoute:
      PlayersPlayerSlugMatchesMatchIdReplayRoute,
  }

const PlayersPlayerSlugMatchesMatchIdRouteWithChildren =
  PlayersPlayerSlugMatchesMatchIdRoute._addFileChildren(
    PlayersPlayerSlugMatchesMatchIdRouteChildren,
  )

interface PlayersPlayerSlugRouteChildren {
  PlayersPlayerSlugAscensionRoute: typeof PlayersPlayerSlugAscensionRouteWithChildren
  PlayersPlayerSlugCareerRoute: typeof PlayersPlayerSlugCareerRoute
  PlayersPlayerSlugCitationsRoute: typeof PlayersPlayerSlugCitationsRoute
  PlayersPlayerSlugCommendationsRoute: typeof PlayersPlayerSlugCommendationsRoute
  PlayersPlayerSlugCompareRoute: typeof PlayersPlayerSlugCompareRoute
  PlayersPlayerSlugHomeRoute: typeof PlayersPlayerSlugHomeRoute
  PlayersPlayerSlugMediaRoute: typeof PlayersPlayerSlugMediaRoute
  PlayersPlayerSlugNotificationsRoute: typeof PlayersPlayerSlugNotificationsRoute
  PlayersPlayerSlugSquadRoute: typeof PlayersPlayerSlugSquadRouteWithChildren
  PlayersPlayerSlugSynthesisRoute: typeof PlayersPlayerSlugSynthesisRoute
  PlayersPlayerSlugCareerCitationsRoute: typeof PlayersPlayerSlugCareerCitationsRoute
  PlayersPlayerSlugCareerCommendationsRoute: typeof PlayersPlayerSlugCareerCommendationsRoute
  PlayersPlayerSlugCareerSeasonPassRoute: typeof PlayersPlayerSlugCareerSeasonPassRoute
  PlayersPlayerSlugCommunityCompareRoute: typeof PlayersPlayerSlugCommunityCompareRoute
  PlayersPlayerSlugCommunityPrestigeRoute: typeof PlayersPlayerSlugCommunityPrestigeRoute
  PlayersPlayerSlugCommunityRelationsRoute: typeof PlayersPlayerSlugCommunityRelationsRoute
  PlayersPlayerSlugMatchesMatchIdRoute: typeof PlayersPlayerSlugMatchesMatchIdRouteWithChildren
  PlayersPlayerSlugPalmaresPrestigeRoute: typeof PlayersPlayerSlugPalmaresPrestigeRoute
  PlayersPlayerSlugPalmaresRelationsRoute: typeof PlayersPlayerSlugPalmaresRelationsRoute
  PlayersPlayerSlugStatsSessionsRoute: typeof PlayersPlayerSlugStatsSessionsRoute
  PlayersPlayerSlugStatsSynthesisRoute: typeof PlayersPlayerSlugStatsSynthesisRoute
  PlayersPlayerSlugStatsTimeseriesRoute: typeof PlayersPlayerSlugStatsTimeseriesRoute
  PlayersPlayerSlugCommunityIndexRoute: typeof PlayersPlayerSlugCommunityIndexRoute
  PlayersPlayerSlugExplorerIndexRoute: typeof PlayersPlayerSlugExplorerIndexRoute
  PlayersPlayerSlugObjectifsIndexRoute: typeof PlayersPlayerSlugObjectifsIndexRoute
  PlayersPlayerSlugPalmaresIndexRoute: typeof PlayersPlayerSlugPalmaresIndexRoute
  PlayersPlayerSlugStatsIndexRoute: typeof PlayersPlayerSlugStatsIndexRoute
}

const PlayersPlayerSlugRouteChildren: PlayersPlayerSlugRouteChildren = {
  PlayersPlayerSlugAscensionRoute: PlayersPlayerSlugAscensionRouteWithChildren,
  PlayersPlayerSlugCareerRoute: PlayersPlayerSlugCareerRoute,
  PlayersPlayerSlugCitationsRoute: PlayersPlayerSlugCitationsRoute,
  PlayersPlayerSlugCommendationsRoute: PlayersPlayerSlugCommendationsRoute,
  PlayersPlayerSlugCompareRoute: PlayersPlayerSlugCompareRoute,
  PlayersPlayerSlugHomeRoute: PlayersPlayerSlugHomeRoute,
  PlayersPlayerSlugMediaRoute: PlayersPlayerSlugMediaRoute,
  PlayersPlayerSlugNotificationsRoute: PlayersPlayerSlugNotificationsRoute,
  PlayersPlayerSlugSquadRoute: PlayersPlayerSlugSquadRouteWithChildren,
  PlayersPlayerSlugSynthesisRoute: PlayersPlayerSlugSynthesisRoute,
  PlayersPlayerSlugCareerCitationsRoute: PlayersPlayerSlugCareerCitationsRoute,
  PlayersPlayerSlugCareerCommendationsRoute:
    PlayersPlayerSlugCareerCommendationsRoute,
  PlayersPlayerSlugCareerSeasonPassRoute:
    PlayersPlayerSlugCareerSeasonPassRoute,
  PlayersPlayerSlugCommunityCompareRoute:
    PlayersPlayerSlugCommunityCompareRoute,
  PlayersPlayerSlugCommunityPrestigeRoute:
    PlayersPlayerSlugCommunityPrestigeRoute,
  PlayersPlayerSlugCommunityRelationsRoute:
    PlayersPlayerSlugCommunityRelationsRoute,
  PlayersPlayerSlugMatchesMatchIdRoute:
    PlayersPlayerSlugMatchesMatchIdRouteWithChildren,
  PlayersPlayerSlugPalmaresPrestigeRoute:
    PlayersPlayerSlugPalmaresPrestigeRoute,
  PlayersPlayerSlugPalmaresRelationsRoute:
    PlayersPlayerSlugPalmaresRelationsRoute,
  PlayersPlayerSlugStatsSessionsRoute: PlayersPlayerSlugStatsSessionsRoute,
  PlayersPlayerSlugStatsSynthesisRoute: PlayersPlayerSlugStatsSynthesisRoute,
  PlayersPlayerSlugStatsTimeseriesRoute: PlayersPlayerSlugStatsTimeseriesRoute,
  PlayersPlayerSlugCommunityIndexRoute: PlayersPlayerSlugCommunityIndexRoute,
  PlayersPlayerSlugExplorerIndexRoute: PlayersPlayerSlugExplorerIndexRoute,
  PlayersPlayerSlugObjectifsIndexRoute: PlayersPlayerSlugObjectifsIndexRoute,
  PlayersPlayerSlugPalmaresIndexRoute: PlayersPlayerSlugPalmaresIndexRoute,
  PlayersPlayerSlugStatsIndexRoute: PlayersPlayerSlugStatsIndexRoute,
}

const PlayersPlayerSlugRouteWithChildren =
  PlayersPlayerSlugRoute._addFileChildren(PlayersPlayerSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  GroupsRoute: GroupsRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  LabChartsRoute: LabChartsRoute,
  OnboardingOpenspartanRoute: OnboardingOpenspartanRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
