/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as PlayersPlayerSlugSynthesisRouteImport } from './routes/players/$playerSlug/synthesis'
import { Route as PlayersPlayerSlugSquadRouteImport } from './routes/players/$playerSlug/squad'
import { Route as PlayersPlayerSlugMediaRouteImport } from './routes/players/$playerSlug/media'
import { Route as PlayersPlayerSlugHomeRouteImport } from './routes/players/$playerSlug/home'
import { Route as PlayersPlayerSlugCareerRouteImport } from './routes/players/$playerSlug/career'
import { Route as PlayersPlayerSlugExplorerIndexRouteImport } from './routes/players/$playerSlug/explorer/index'
import { Route as PlayersPlayerSlugStatsHistoryRouteImport } from './routes/players/$playerSlug/stats/history'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugSynthesisRoute =
  PlayersPlayerSlugSynthesisRouteImport.update({
    id: '/synthesis',
    path: '/synthesis',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugSquadRoute = PlayersPlayerSlugSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugMediaRoute = PlayersPlayerSlugMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugHomeRoute = PlayersPlayerSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugCareerRoute = PlayersPlayerSlugCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugExplorerIndexRoute =
  PlayersPlayerSlugExplorerIndexRouteImport.update({
    id: '/explorer/',
    path: '/explorer/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsHistoryRoute =
  PlayersPlayerSlugStatsHistoryRouteImport.update({
    id: '/stats/history',
    path: '/stats/history',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/stats/history': typeof PlayersPlayerSlugStatsHistoryRoute
  '/players/$playerSlug/explorer/': typeof PlayersPlayerSlugExplorerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/stats/history': typeof PlayersPlayerSlugStatsHistoryRoute
  '/players/$playerSlug/explorer': typeof PlayersPlayerSlugExplorerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/stats/history': typeof PlayersPlayerSlugStatsHistoryRoute
  '/players/$playerSlug/explorer/': typeof PlayersPlayerSlugExplorerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/setup'
    | '/players/$playerSlug'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/stats/history'
    | '/players/$playerSlug/explorer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/setup'
    | '/players/$playerSlug'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/stats/history'
    | '/players/$playerSlug/explorer'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/setup'
    | '/players/$playerSlug'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/stats/history'
    | '/players/$playerSlug/explorer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug/synthesis': {
      id: '/players/$playerSlug/synthesis'
      path: '/synthesis'
      fullPath: '/players/$playerSlug/synthesis'
      preLoaderRoute: typeof PlayersPlayerSlugSynthesisRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/squad': {
      id: '/players/$playerSlug/squad'
      path: '/squad'
      fullPath: '/players/$playerSlug/squad'
      preLoaderRoute: typeof PlayersPlayerSlugSquadRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/media': {
      id: '/players/$playerSlug/media'
      path: '/media'
      fullPath: '/players/$playerSlug/media'
      preLoaderRoute: typeof PlayersPlayerSlugMediaRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/home': {
      id: '/players/$playerSlug/home'
      path: '/home'
      fullPath: '/players/$playerSlug/home'
      preLoaderRoute: typeof PlayersPlayerSlugHomeRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/career': {
      id: '/players/$playerSlug/career'
      path: '/career'
      fullPath: '/players/$playerSlug/career'
      preLoaderRoute: typeof PlayersPlayerSlugCareerRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/explorer/': {
      id: '/players/$playerSlug/explorer/'
      path: '/explorer'
      fullPath: '/players/$playerSlug/explorer/'
      preLoaderRoute: typeof PlayersPlayerSlugExplorerIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/history': {
      id: '/players/$playerSlug/stats/history'
      path: '/stats/history'
      fullPath: '/players/$playerSlug/stats/history'
      preLoaderRoute: typeof PlayersPlayerSlugStatsHistoryRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
  }
}

interface PlayersPlayerSlugRouteChildren {
  PlayersPlayerSlugCareerRoute: typeof PlayersPlayerSlugCareerRoute
  PlayersPlayerSlugHomeRoute: typeof PlayersPlayerSlugHomeRoute
  PlayersPlayerSlugMediaRoute: typeof PlayersPlayerSlugMediaRoute
  PlayersPlayerSlugSquadRoute: typeof PlayersPlayerSlugSquadRoute
  PlayersPlayerSlugSynthesisRoute: typeof PlayersPlayerSlugSynthesisRoute
  PlayersPlayerSlugStatsHistoryRoute: typeof PlayersPlayerSlugStatsHistoryRoute
  PlayersPlayerSlugExplorerIndexRoute: typeof PlayersPlayerSlugExplorerIndexRoute
}

const PlayersPlayerSlugRouteChildren: PlayersPlayerSlugRouteChildren = {
  PlayersPlayerSlugCareerRoute: PlayersPlayerSlugCareerRoute,
  PlayersPlayerSlugHomeRoute: PlayersPlayerSlugHomeRoute,
  PlayersPlayerSlugMediaRoute: PlayersPlayerSlugMediaRoute,
  PlayersPlayerSlugSquadRoute: PlayersPlayerSlugSquadRoute,
  PlayersPlayerSlugSynthesisRoute: PlayersPlayerSlugSynthesisRoute,
  PlayersPlayerSlugStatsHistoryRoute: PlayersPlayerSlugStatsHistoryRoute,
  PlayersPlayerSlugExplorerIndexRoute: PlayersPlayerSlugExplorerIndexRoute,
}

const PlayersPlayerSlugRouteWithChildren =
  PlayersPlayerSlugRoute._addFileChildren(PlayersPlayerSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
