/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as PlayersPlayerSlugSynthesisRouteImport } from './routes/players/$playerSlug/synthesis'
import { Route as PlayersPlayerSlugSquadRouteImport } from './routes/players/$playerSlug/squad'
import { Route as PlayersPlayerSlugMediaRouteImport } from './routes/players/$playerSlug/media'
import { Route as PlayersPlayerSlugLastMatchRouteImport } from './routes/players/$playerSlug/last-match'
import { Route as PlayersPlayerSlugHomeRouteImport } from './routes/players/$playerSlug/home'
import { Route as PlayersPlayerSlugCareerRouteImport } from './routes/players/$playerSlug/career'
import { Route as PlayersPlayerSlugExplorerIndexRouteImport } from './routes/players/$playerSlug/explorer/index'
import { Route as PlayersPlayerSlugStatsTimeseriesRouteImport } from './routes/players/$playerSlug/stats/timeseries'
import { Route as PlayersPlayerSlugStatsSessionsRouteImport } from './routes/players/$playerSlug/stats/sessions'
import { Route as PlayersPlayerSlugStatsHistoryRouteImport } from './routes/players/$playerSlug/stats/history'
import { Route as PlayersPlayerSlugProfileCitationsRouteImport } from './routes/players/$playerSlug/profile/citations'
import { Route as PlayersPlayerSlugExplorerMatchesMatchIdRouteImport } from './routes/players/$playerSlug/explorer/matches/$matchId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugSynthesisRoute =
  PlayersPlayerSlugSynthesisRouteImport.update({
    id: '/synthesis',
    path: '/synthesis',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugSquadRoute = PlayersPlayerSlugSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugMediaRoute = PlayersPlayerSlugMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugLastMatchRoute =
  PlayersPlayerSlugLastMatchRouteImport.update({
    id: '/last-match',
    path: '/last-match',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugHomeRoute = PlayersPlayerSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugCareerRoute = PlayersPlayerSlugCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => PlayersPlayerSlugRoute,
} as any)
const PlayersPlayerSlugExplorerIndexRoute =
  PlayersPlayerSlugExplorerIndexRouteImport.update({
    id: '/explorer/',
    path: '/explorer/',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsTimeseriesRoute =
  PlayersPlayerSlugStatsTimeseriesRouteImport.update({
    id: '/stats/timeseries',
    path: '/stats/timeseries',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsSessionsRoute =
  PlayersPlayerSlugStatsSessionsRouteImport.update({
    id: '/stats/sessions',
    path: '/stats/sessions',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugStatsHistoryRoute =
  PlayersPlayerSlugStatsHistoryRouteImport.update({
    id: '/stats/history',
    path: '/stats/history',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugProfileCitationsRoute =
  PlayersPlayerSlugProfileCitationsRouteImport.update({
    id: '/profile/citations',
    path: '/profile/citations',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)
const PlayersPlayerSlugExplorerMatchesMatchIdRoute =
  PlayersPlayerSlugExplorerMatchesMatchIdRouteImport.update({
    id: '/explorer/matches/$matchId',
    path: '/explorer/matches/$matchId',
    getParentRoute: () => PlayersPlayerSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/last-match': typeof PlayersPlayerSlugLastMatchRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/profile/citations': typeof PlayersPlayerSlugProfileCitationsRoute
  '/players/$playerSlug/stats/history': typeof PlayersPlayerSlugStatsHistoryRoute
  '/players/$playerSlug/stats/sessions': typeof PlayersPlayerSlugStatsSessionsRoute
  '/players/$playerSlug/stats/timeseries': typeof PlayersPlayerSlugStatsTimeseriesRoute
  '/players/$playerSlug/explorer/': typeof PlayersPlayerSlugExplorerIndexRoute
  '/players/$playerSlug/explorer/matches/$matchId': typeof PlayersPlayerSlugExplorerMatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/last-match': typeof PlayersPlayerSlugLastMatchRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/profile/citations': typeof PlayersPlayerSlugProfileCitationsRoute
  '/players/$playerSlug/stats/history': typeof PlayersPlayerSlugStatsHistoryRoute
  '/players/$playerSlug/stats/sessions': typeof PlayersPlayerSlugStatsSessionsRoute
  '/players/$playerSlug/stats/timeseries': typeof PlayersPlayerSlugStatsTimeseriesRoute
  '/players/$playerSlug/explorer': typeof PlayersPlayerSlugExplorerIndexRoute
  '/players/$playerSlug/explorer/matches/$matchId': typeof PlayersPlayerSlugExplorerMatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRouteWithChildren
  '/players/$playerSlug/career': typeof PlayersPlayerSlugCareerRoute
  '/players/$playerSlug/home': typeof PlayersPlayerSlugHomeRoute
  '/players/$playerSlug/last-match': typeof PlayersPlayerSlugLastMatchRoute
  '/players/$playerSlug/media': typeof PlayersPlayerSlugMediaRoute
  '/players/$playerSlug/squad': typeof PlayersPlayerSlugSquadRoute
  '/players/$playerSlug/synthesis': typeof PlayersPlayerSlugSynthesisRoute
  '/players/$playerSlug/profile/citations': typeof PlayersPlayerSlugProfileCitationsRoute
  '/players/$playerSlug/stats/history': typeof PlayersPlayerSlugStatsHistoryRoute
  '/players/$playerSlug/stats/sessions': typeof PlayersPlayerSlugStatsSessionsRoute
  '/players/$playerSlug/stats/timeseries': typeof PlayersPlayerSlugStatsTimeseriesRoute
  '/players/$playerSlug/explorer/': typeof PlayersPlayerSlugExplorerIndexRoute
  '/players/$playerSlug/explorer/matches/$matchId': typeof PlayersPlayerSlugExplorerMatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/lab'
    | '/settings'
    | '/setup'
    | '/players/$playerSlug'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/last-match'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/profile/citations'
    | '/players/$playerSlug/stats/history'
    | '/players/$playerSlug/stats/sessions'
    | '/players/$playerSlug/stats/timeseries'
    | '/players/$playerSlug/explorer/'
    | '/players/$playerSlug/explorer/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/lab'
    | '/settings'
    | '/setup'
    | '/players/$playerSlug'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/last-match'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/profile/citations'
    | '/players/$playerSlug/stats/history'
    | '/players/$playerSlug/stats/sessions'
    | '/players/$playerSlug/stats/timeseries'
    | '/players/$playerSlug/explorer'
    | '/players/$playerSlug/explorer/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/lab'
    | '/settings'
    | '/setup'
    | '/players/$playerSlug'
    | '/players/$playerSlug/career'
    | '/players/$playerSlug/home'
    | '/players/$playerSlug/last-match'
    | '/players/$playerSlug/media'
    | '/players/$playerSlug/squad'
    | '/players/$playerSlug/synthesis'
    | '/players/$playerSlug/profile/citations'
    | '/players/$playerSlug/stats/history'
    | '/players/$playerSlug/stats/sessions'
    | '/players/$playerSlug/stats/timeseries'
    | '/players/$playerSlug/explorer/'
    | '/players/$playerSlug/explorer/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  LabRoute: typeof LabRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug/synthesis': {
      id: '/players/$playerSlug/synthesis'
      path: '/synthesis'
      fullPath: '/players/$playerSlug/synthesis'
      preLoaderRoute: typeof PlayersPlayerSlugSynthesisRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/squad': {
      id: '/players/$playerSlug/squad'
      path: '/squad'
      fullPath: '/players/$playerSlug/squad'
      preLoaderRoute: typeof PlayersPlayerSlugSquadRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/media': {
      id: '/players/$playerSlug/media'
      path: '/media'
      fullPath: '/players/$playerSlug/media'
      preLoaderRoute: typeof PlayersPlayerSlugMediaRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/last-match': {
      id: '/players/$playerSlug/last-match'
      path: '/last-match'
      fullPath: '/players/$playerSlug/last-match'
      preLoaderRoute: typeof PlayersPlayerSlugLastMatchRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/home': {
      id: '/players/$playerSlug/home'
      path: '/home'
      fullPath: '/players/$playerSlug/home'
      preLoaderRoute: typeof PlayersPlayerSlugHomeRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/career': {
      id: '/players/$playerSlug/career'
      path: '/career'
      fullPath: '/players/$playerSlug/career'
      preLoaderRoute: typeof PlayersPlayerSlugCareerRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/explorer/': {
      id: '/players/$playerSlug/explorer/'
      path: '/explorer'
      fullPath: '/players/$playerSlug/explorer/'
      preLoaderRoute: typeof PlayersPlayerSlugExplorerIndexRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/timeseries': {
      id: '/players/$playerSlug/stats/timeseries'
      path: '/stats/timeseries'
      fullPath: '/players/$playerSlug/stats/timeseries'
      preLoaderRoute: typeof PlayersPlayerSlugStatsTimeseriesRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/sessions': {
      id: '/players/$playerSlug/stats/sessions'
      path: '/stats/sessions'
      fullPath: '/players/$playerSlug/stats/sessions'
      preLoaderRoute: typeof PlayersPlayerSlugStatsSessionsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/stats/history': {
      id: '/players/$playerSlug/stats/history'
      path: '/stats/history'
      fullPath: '/players/$playerSlug/stats/history'
      preLoaderRoute: typeof PlayersPlayerSlugStatsHistoryRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/profile/citations': {
      id: '/players/$playerSlug/profile/citations'
      path: '/profile/citations'
      fullPath: '/players/$playerSlug/profile/citations'
      preLoaderRoute: typeof PlayersPlayerSlugProfileCitationsRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
    '/players/$playerSlug/explorer/matches/$matchId': {
      id: '/players/$playerSlug/explorer/matches/$matchId'
      path: '/explorer/matches/$matchId'
      fullPath: '/players/$playerSlug/explorer/matches/$matchId'
      preLoaderRoute: typeof PlayersPlayerSlugExplorerMatchesMatchIdRouteImport
      parentRoute: typeof PlayersPlayerSlugRoute
    }
  }
}

interface PlayersPlayerSlugRouteChildren {
  PlayersPlayerSlugCareerRoute: typeof PlayersPlayerSlugCareerRoute
  PlayersPlayerSlugHomeRoute: typeof PlayersPlayerSlugHomeRoute
  PlayersPlayerSlugLastMatchRoute: typeof PlayersPlayerSlugLastMatchRoute
  PlayersPlayerSlugMediaRoute: typeof PlayersPlayerSlugMediaRoute
  PlayersPlayerSlugSquadRoute: typeof PlayersPlayerSlugSquadRoute
  PlayersPlayerSlugSynthesisRoute: typeof PlayersPlayerSlugSynthesisRoute
  PlayersPlayerSlugProfileCitationsRoute: typeof PlayersPlayerSlugProfileCitationsRoute
  PlayersPlayerSlugStatsHistoryRoute: typeof PlayersPlayerSlugStatsHistoryRoute
  PlayersPlayerSlugStatsSessionsRoute: typeof PlayersPlayerSlugStatsSessionsRoute
  PlayersPlayerSlugStatsTimeseriesRoute: typeof PlayersPlayerSlugStatsTimeseriesRoute
  PlayersPlayerSlugExplorerIndexRoute: typeof PlayersPlayerSlugExplorerIndexRoute
  PlayersPlayerSlugExplorerMatchesMatchIdRoute: typeof PlayersPlayerSlugExplorerMatchesMatchIdRoute
}

const PlayersPlayerSlugRouteChildren: PlayersPlayerSlugRouteChildren = {
  PlayersPlayerSlugCareerRoute: PlayersPlayerSlugCareerRoute,
  PlayersPlayerSlugHomeRoute: PlayersPlayerSlugHomeRoute,
  PlayersPlayerSlugLastMatchRoute: PlayersPlayerSlugLastMatchRoute,
  PlayersPlayerSlugMediaRoute: PlayersPlayerSlugMediaRoute,
  PlayersPlayerSlugSquadRoute: PlayersPlayerSlugSquadRoute,
  PlayersPlayerSlugSynthesisRoute: PlayersPlayerSlugSynthesisRoute,
  PlayersPlayerSlugProfileCitationsRoute:
    PlayersPlayerSlugProfileCitationsRoute,
  PlayersPlayerSlugStatsHistoryRoute: PlayersPlayerSlugStatsHistoryRoute,
  PlayersPlayerSlugStatsSessionsRoute: PlayersPlayerSlugStatsSessionsRoute,
  PlayersPlayerSlugStatsTimeseriesRoute: PlayersPlayerSlugStatsTimeseriesRoute,
  PlayersPlayerSlugExplorerIndexRoute: PlayersPlayerSlugExplorerIndexRoute,
  PlayersPlayerSlugExplorerMatchesMatchIdRoute:
    PlayersPlayerSlugExplorerMatchesMatchIdRoute,
}

const PlayersPlayerSlugRouteWithChildren =
  PlayersPlayerSlugRoute._addFileChildren(PlayersPlayerSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  LabRoute: LabRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
