package ops

// seed_citation_data.go — table de donnees: mapping medaille -> citation.
// Littéral de données (exempt de la regle 80L/fonction : data table).

// defaultCitationMappings — 98 règles citations (88 portées de l'ancien
// scripts/populate_citation_mappings.py, + 10 citations d'objectif v7.2.1).
//
// Catégories : Mode de jeu, Multijoueur, Spartan Companies, Véhicule, Arme,
// Ennemi (PVE) + composites.
//
// Source de vérité unique (le script Python a été supprimé avec la migration) :
// toute modification impose un re-seed + un backfill citations (docs/COMMENDATIONS.md).
//
// littéral `return []CitationMapping{...}` : funlen mord sur les lignes, pas les
// statements). maintidx n'est pas activé dans .golangci.yml au 2026-07 (absent de
// linters.enable et du set "standard") — la directive est donc inerte aujourd'hui ;
// conservée pour documenter l'intention si le linter est un jour activé, plutôt
// que de retirer sans certitude et risquer un futur gate rouge silencieux.
//
//nolint:funlen,maintidx // Données de seed — préfère lisibilité linéaire (un seul
func defaultCitationMappings() []CitationMapping {
	// Phase 6.5 (2026-04-28, commit a1d25325) a renommé les sous-dossiers vers
	// les slugs canoniques longs. Tout chemin émis ici doit utiliser ces slugs,
	// sinon le seed UPSERT écrase image_path avec un chemin 404.
	const wpH5 = "static/commendations/halo_5_guardians/"
	const wpHI = "static/commendations/halo_infinite/"
	return []CitationMapping{
		// ── PVP — Mode de jeu (11) ────────────────────────────────────
		// v7.2 (décision utilisateur) — BASCULE DES 4 CITATIONS D'OBJECTIF vers la
		// source objective_stat (colonnes match_objective_stats_latest), plus fiable
		// que les awards personal_score : charge→zone_captures, got_you→flag_returns,
		// stakeholder→zone_secures, flag_carrier_hunter→flag_carriers_killed. La
		// progression est recalculée depuis l'historique au backfill citations
		// (--citations-recompute-all) : re-seed puis rejeu requis (local + prod).
		{Norm: citationNormCharge, Display: "À la charge", MappingType: mappingTypeObjectiveStat,
			StatName: "zone_captures", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_À_la_charge.png",
			Category:    citationCatModeJeu,
			Description: "Prenez le contrôle d'une base dans n'importe quelle partie matchmaking Bases.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: "forced_annexation", Display: "Annexion forcée", MappingType: mappingTypeCustom,
			CustomFunction: "compute_annexion_forcee", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Annexion_forcée.png",
			Category:    citationCatModeJeu,
			Description: "Prenez le contrôle de 3 bases sans mourir dans n'importe quelle partie matchmaking Bases.",
			TierTargets: tierTargets3_6_9_15_30},
		{Norm: "assistant", Display: "Assistant", MappingType: mappingTypeStat,
			StatName: "assists", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Assistant.png",
			Category:    citationCatModeJeu,
			Description: "Remportez n'importe quelle médaille d'assistance en Zone de combat.",
			TierTargets: "25,50,75,125,250"},
		{Norm: "bulldozer", Display: "Bulldozer", MappingType: mappingTypeCustom,
			CustomFunction: "compute_bulldozer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Bulldozer.png",
			Category:    citationCatModeJeu,
			Description: "Terminez n'importe quelle partie matchmaking Assassin avec un FDA supérieur à 8.",
			TierTargets: tierTargets3_6_9_15_30},
		// I7 (2026-07-24) — DÉCISION UTILISATEUR : flag_defender DÉSACTIVÉE (Enabled=false).
		// Aucun award d'ingestion (refdata_personal_scores.go) ne mesure la défense de SON
		// PROPRE drapeau de façon non ambiguë : "carrier_killed" (seul candidat direct) veut
		// dire « tuer le porte-drapeau ENNEMI » = flag_carrier_hunter, pas la défense. La
		// citation reste listée (inventaire + parité EN) mais le moteur l'ignore
		// (loadFullCitationMappings : WHERE enabled IS NOT FALSE). Candidat futur si un award
		// dédié apparaît : "carrier_stopped" (objective — stopper le porteur ennemi de VOTRE
		// drapeau). Non enfant d'un composite → aucun composite rendu inatteignable.
		{Norm: "flag_defender", Display: "Défenseur du drapeau", MappingType: mappingTypeAward,
			AwardName: "carrier_killed", AwardCategory: awardCategoryObjective, Enabled: false,
			ImagePath:   wpH5 + "H5G_citation_Défenseur_du_drapeau.png",
			Category:    citationCatModeJeu,
			Description: "Protégez le drapeau de votre équipe dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: citationNormGotYou, Display: "Je te tiens !", MappingType: mappingTypeObjectiveStat,
			StatName: "flag_returns", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Je_te_tiens_!.png",
			Category:    citationCatModeJeu,
			Description: "Rapportez le drapeau de votre équipe dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: citationNormStakeholder, Display: "Partie prenante", MappingType: mappingTypeObjectiveStat,
			StatName: "zone_secures", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Partie_prenante.png",
			Category:    citationCatModeJeu,
			Description: "Défendez une base appartenant à votre équipe dans n'importe quelle partie matchmaking Bases.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: citationNormFlagCarrierHunter, Display: "Sus au porteur du drapeau", MappingType: mappingTypeObjectiveStat,
			StatName: "flag_carriers_killed", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Sus_au_porteur_du_drapeau.png",
			Category:    citationCatModeJeu,
			Description: "Tuez un porte-drapeau ennemi dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: "flag_victory", Display: "Victoire au drapeau", MappingType: mappingTypeCustom,
			CustomFunction: "compute_wins_ctf", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Victoire_au_drapeau.png",
			Category:    citationCatModeJeu,
			Description: "Remportez n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets5_10_15_25_50},
		{Norm: "slayer_victory", Display: "Victoire en assassin", MappingType: mappingTypeCustom,
			CustomFunction: "compute_wins_slayer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Victoire_en_Assassin.png",
			Category:    citationCatModeJeu,
			Description: "Remportez une partie d'Assassin en équipe.",
			TierTargets: tierTargets5_10_15_25_50},
		{Norm: "strongholds_victory", Display: "Victoire en bases", MappingType: mappingTypeCustom,
			CustomFunction: "compute_wins_strongholds", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Victoire_en_Bases.png",
			Category:    citationCatModeJeu,
			Description: "Remportez n'importe quelle partie matchmaking Bases.",
			TierTargets: tierTargets5_10_15_25_50},

		// ── PVP — Mode de jeu · objectifs CTF/Zones/Oddball (10, v7.2.1) ──────
		// DÉCISION UTILISATEUR (2026-07-25) : sur les 19 colonnes de
		// match_objective_stats restées libres après la bascule v7.2, 10 sont retenues
		// et 9 écartées (« elles n'en valent pas la peine »). Ne pas re-proposer les 9.
		// Paliers calibrés sur les données réelles — cf. le bloc de constantes
		// tierTargets d'objectif (seed.go) : NE PAS les réaligner sur les paliers
		// génériques, quatre de ces citations deviendraient inatteignables.
		// Ordre du bloc : CTF, puis Zones, puis Oddball — celui d'objectiveStatColumns
		// (internal/sync/citations.go), et non l'ordre alphabétique du bloc précédent.
		//
		// VISUELS PROVISOIRES — « Capture du drapeau » et « Vol du drapeau » pointent deux
		// SVG bouche-trous générés en interne, uniquement pour que la chaîne soit
		// complète et testable en local (pas de vignette cassée). L'utilisateur produit
		// ses propres visuels sous Photoshop ; cibles attendues :
		//   static/commendations/halo_infinite/HI_citation_Capture_du_drapeau.png
		//   static/commendations/halo_infinite/HI_citation_Vol_du_drapeau.png
		// Remplacement = changer `.svg` en `.png` dans les deux ImagePath ci-dessous
		// puis re-seeder (`levelup seed citation-mappings`) — rien d'autre à toucher.
		// NE PAS DÉPLOYER EN PROD avec les SVG (blocage acté, plan V721-03).
		{Norm: citationNormFlagCaptures, Display: "Capture du drapeau", MappingType: mappingTypeObjectiveStat,
			StatName: "flag_captures", Enabled: true,
			ImagePath:   wpHI + "HI_citation_Capture_du_drapeau.svg",
			Category:    citationCatModeJeu,
			Description: "Capturez le drapeau ennemi dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets10_25_50_75_125},
		{Norm: citationNormFlagSecures, Display: "Sécurisation du drapeau", MappingType: mappingTypeObjectiveStat,
			StatName: "flag_secures", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Protecteur.png",
			Category:    citationCatModeJeu,
			Description: "Sécurisez le drapeau de votre équipe dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets50_100_200_350_600},
		{Norm: citationNormFlagSteals, Display: "Vol du drapeau", MappingType: mappingTypeObjectiveStat,
			StatName: "flag_steals", Enabled: true,
			ImagePath:   wpHI + "HI_citation_Vol_du_drapeau.svg",
			Category:    citationCatModeJeu,
			Description: "Volez le drapeau ennemi à sa base dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets25_50_100_175_300},
		{Norm: citationNormReturnerTakedown, Display: "Chasse au rapatrieur", MappingType: mappingTypeObjectiveStat,
			StatName: "flag_returners_killed", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Not_so_fast.png",
			Category:    citationCatModeJeu,
			Description: "Tuez les adversaires qui rapportent leur propre drapeau dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets5_10_20_35_60},
		{Norm: citationNormUnstoppableCarrier, Display: "Porteur imparable", MappingType: mappingTypeObjectiveStat,
			StatName: "kills_as_flag_carrier", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Imparable.png",
			Category:    citationCatModeJeu,
			Description: "Tuez un adversaire alors que vous portez le drapeau dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets1_2_3_5_10},
		{Norm: citationNormAggressiveReturn, Display: "Rapatriement agressif", MappingType: mappingTypeObjectiveStat,
			StatName: "kills_as_flag_returner", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Body_Guard.png",
			Category:    citationCatModeJeu,
			Description: "Tuez un adversaire pendant que vous rapportez le drapeau de votre équipe dans n'importe quelle partie matchmaking Capture du drapeau.",
			TierTargets: tierTargets5_10_20_30_50},
		{Norm: citationNormZoneDefense, Display: "Défense de zone", MappingType: mappingTypeObjectiveStat,
			StatName: "zone_defensive_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_My_castle.png",
			Category:    citationCatModeJeu,
			Description: "Tuez un adversaire dans une zone contrôlée par votre équipe dans n'importe quelle partie matchmaking Bases.",
			TierTargets: tierTargets25_50_100_200_350},
		{Norm: citationNormUntouchableCarrier, Display: "Crâne intouchable", MappingType: mappingTypeObjectiveStat,
			StatName: "kills_as_skull_carrier", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Éradicateur.png",
			Category:    citationCatModeJeu,
			Description: "Tuez un adversaire alors que vous portez le crâne dans n'importe quelle partie matchmaking Oddball.",
			TierTargets: tierTargets1_2_3_5_10},
		{Norm: citationNormSkullCarrierTakedown, Display: "Chasse au porteur", MappingType: mappingTypeObjectiveStat,
			StatName: "skull_carriers_killed", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Somebody_call_for_an_extermination%3F.png",
			Category:    citationCatModeJeu,
			Description: "Tuez le porteur du crâne adverse dans n'importe quelle partie matchmaking Oddball.",
			TierTargets: tierTargets2_5_10_20_40},
		{Norm: citationNormSkullGrabs, Display: "Prise du crâne", MappingType: mappingTypeObjectiveStat,
			StatName: "skull_grabs", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Is_that_my_ball%3F.png",
			Category:    citationCatModeJeu,
			Description: "Emparez-vous du crâne dans n'importe quelle partie matchmaking Oddball.",
			TierTargets: tierTargets2_5_10_20_40},

		// ── PVP — Véhicule (2) + Grenade (2) ──────────────────────────
		{Norm: "splatter", Display: "Écrasement", MappingType: mappingTypeMedal, MedalID: 221693153, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Écrasement.png",
			Category:    citationCatVehicule,
			Description: "Écrasez un Spartan adverse avec un véhicule.",
			TierTargets: tierTargets10_20_30_50_100, Subcategory: citationSubGeneral},
		// BUG C (I7, 2026-07-24) : `driver` et `road_trip` pointaient tous deux la
		// médaille 3169118333 (« Violence routière »/vehicle-kill). Le nom EN de
		// cette citation est « Wheelman » (cf. citationDisplayEN) = médaille de
		// pilote-assist (categorie "assists" dans medal_category_table.go:120),
		// medal_id 2926348688 → remap ici. Distinct de 3169118333 (vehicles), ce
		// qui lève la collision côté `driver`.
		{Norm: "driver", Display: "Pilote", MappingType: mappingTypeMedal, MedalID: 2926348688, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Pilote.png",
			Category:    citationCatVehicule,
			Description: "Décrochez des médailles de pilote.",
			TierTargets: tierTargets10_20_30_50_100, Subcategory: citationSubGeneral},
		{Norm: "frag_grenade", Display: "Grenade à fragmentation", MappingType: mappingTypeMedal, MedalID: 2648272972, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Grenade_à_fragmentation.png",
			Category:    citationCatArme,
			Description: "Tuez un Spartan adverse à l'aide d'une grenade à fragmentation.",
			TierTargets: tierTargets5_10_15_25_50, Subcategory: "Grenade"},
		{Norm: "plasma_grenade", Display: "Grenade à plasma", MappingType: mappingTypeMedal, MedalID: 3655682764, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Grenade_à_plasma.png",
			Category:    citationCatArme,
			Description: "Tuez un Spartan adverse à l'aide d'une grenade à plasma.",
			TierTargets: "2,4,6,10,20", Subcategory: "Grenade"},

		// ── PVP — Multijoueur (10) ────────────────────────────────────
		{Norm: "assassin", Display: "Assassin", MappingType: mappingTypeMedal, MedalID: 548533137, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Assassin.png",
			Category:    citationCatMultijoueur,
			Description: "Assassinez des Spartans adverses.",
			TierTargets: tierTargets5_10_15_25_50},
		{Norm: "spartan_carnage", Display: "Carnage de Spartans", MappingType: mappingTypeMedal,
			MedalIDs:    "2780740615,4261842076,418532952,1486797009,710323196,1720896992,2567026752,2875941471",
			Enabled:     true,
			ImagePath:   wpH5 + "H5G_citation_Carnage_de_Spartans.png",
			Category:    citationCatMultijoueur,
			Description: "Tuez plusieurs Spartans adverses sans mourir.",
			TierTargets: tierTargets3_6_9_15_30},
		{Norm: "close_combat", Display: "Combat rapproché", MappingType: mappingTypeStat,
			StatName: "melee_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Combat_rapproché.png",
			Category:    citationCatMultijoueur,
			Description: "Remportez n'importe quelle médaille de combat rapproché.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: "opportunist", Display: "Combattant opportuniste", MappingType: mappingTypeMedal,
			MedalIDs:    "622331684,2063152177,4261842076,2137071619,1486797009,1430343434,2242633421",
			Enabled:     true,
			ImagePath:   wpH5 + "H5G_citation_Combattant_opportuniste.png",
			Category:    citationCatMultijoueur,
			Description: "Remportez n'importe quelle médaille d'aptitude au combat.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: "multikill", Display: "Multifrag", MappingType: mappingTypeMedal, MedalID: 622331684, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Multifrag.png",
			Category:    citationCatMultijoueur,
			Description: "Tuez rapidement plusieurs Spartans adverses.",
			TierTargets: tierTargets3_6_9_15_30},
		{Norm: "melee_fighter", Display: "Pugilat", MappingType: mappingTypeStat,
			StatName: "melee_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Pugilat.png",
			Category:    citationCatMultijoueur,
			Description: "Tuez un Spartan ennemi d'une attaque rapprochée.",
			TierTargets: tierTargets5_10_15_25_50},
		{Norm: "headshot", Display: "Tir à la tête", MappingType: mappingTypeStat,
			StatName: "headshot_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Tir_à_la_tête.png",
			Category:    citationCatMultijoueur,
			Description: "Tuez un Spartan ennemi d'un tir à la tête.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: "spartan_killer", Display: "Tueur de Spartans", MappingType: mappingTypeStat,
			StatName: "kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Tueur_de_Spartans.png",
			Category:    citationCatMultijoueur,
			Description: "Éliminez les Spartans ennemis.",
			TierTargets: "20,40,60,100,200"},
		{Norm: "eagle_eye", Display: "Œil de lynx", MappingType: mappingTypeMedal, MedalID: 1512363953, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Œil_de_lynx.png",
			Category:    citationCatMultijoueur,
			Description: "Tuez un Spartan adverse en pleine santé à l'aide d'une arme de précision sans manquer un seul coup.",
			TierTargets: tierTargets10_20_30_50_100},
		{Norm: "avenger", Display: "Vengeur", MappingType: mappingTypeMedal, MedalID: 9000000001, Enabled: true,
			ImagePath:   wpH5 + "Assassin_commendation.png",
			Category:    citationCatMultijoueur,
			Description: "Tuez l'ennemi responsable de votre mort précédente.",
			TierTargets: "5,15,30,55,105"},

		// ── PVP — Spartan Companies (15) ──────────────────────────────
		{Norm: "flag_em_down", Display: "Sors les drapeaux", MappingType: mappingTypeCustom,
			CustomFunction: "compute_flag_em_down", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Flag_'em_down.png",
			Category:    citationCatSpartanCompanies,
			Description: "Obtenir une des médailles suivantes : Interception, Bataille de drapeaux, Frag du porteur, Retour du drapeau, Défense du drapeau",
			TierTargets: "1000,2000,3000,4800,9700"},
		{Norm: "grand_theft", Display: "Vol à la tire", MappingType: mappingTypeCustom,
			CustomFunction: "compute_hijack", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Grand_Theft.png",
			Category:    citationCatSpartanCompanies,
			Description: "Aborder un véhicule ou un véhicule aérien",
			TierTargets: "200,400,600,960,1940"},
		{Norm: "helping_hand", Display: "Coup de main", MappingType: mappingTypeStat,
			StatName: "assists", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Helping_Hand.png",
			Category:    citationCatSpartanCompanies,
			Description: "Obtenir n'importe quelle assistance",
			TierTargets: "20000,40000,60000,96000,194400"},
		{Norm: "im_just_perfect", Display: "Zéro défaut", MappingType: mappingTypeMedal, MedalID: 1512363953, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_I'm_just_perfect.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un joueur avec une arme de précision sans manquer un tir",
			TierTargets: "2000,4000,6000,9600,19400"},
		{Norm: "lawnmower", Display: "Tondeuse", MappingType: mappingTypeMedal, MedalID: 221693153, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Lawnmower.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un adversaire en l'écrasant avec un véhicule",
			TierTargets: "500,1000,1500,2400,4900"},
		{Norm: "look_ma_no_pin", Display: "Regarde maman, sans goupille", MappingType: mappingTypeStat,
			StatName: "grenade_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Look_ma_no_pin.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un Spartan ennemi avec n'importe quelle grenade",
			TierTargets: "4000,8000,12000,19200,38900"},
		{Norm: "lucky", Display: "Lucky", MappingType: mappingTypeMedal,
			MedalIDs: "3905838030,3091261182", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Lucky.png",
			Category:    citationCatSpartanCompanies,
			Description: "Obtenir les médailles La chance, Chargeur vide, Sayonara ou Boulet de canon",
			TierTargets: "400,800,1200,1920,3880"},
		{Norm: "no_hard_feelings", Display: "Sans rancune", MappingType: mappingTypeStat,
			StatName: "kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_No_Hard_Feelings.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer des Spartans ennemis",
			TierTargets: "50000,100000,150000,240000,486000"},
		{Norm: "positive_contribution", Display: "Positive contribution", MappingType: mappingTypeCustom,
			CustomFunction: "compute_bulldozer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Positive_contribution.png",
			Category:    citationCatSpartanCompanies,
			Description: "Finir avec FDA supérieur à 8 dans n'importe quelle partie Assassin en matchmaking",
			TierTargets: "300,600,900,1440,2960"},
		{Norm: "power_play", Display: "Coup de force", MappingType: mappingTypeStat,
			StatName: "power_weapon_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Power_play.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un Spartan ennemi avec une arme puissante",
			TierTargets: "10000,20000,30000,48000,97200"},
		// I7 (2026-07-24) — DÉCISION UTILISATEUR : road_trip remappée sur la médaille
		// d'ÉCRASEMENT (Splatter) 221693153, présente au catalogue Infinite — faisceau
		// concordant : medal_category_table.go la classe "vehicles" ; la citation `splatter`
		// (Display « Écrasement », EN « Splatter ») pointe déjà cette médaille ; asset_labels_fr
		// mappe "Splatter"="Écrasement". L'ancien medal_id 3169118333 (« Violence routière »)
		// n'est plus référencé par aucune citation. Duplication de médaille intentionnelle
		// (comme splatter/lawnmower) : road_trip conserve son palier Spartan Company élevé
		// (grind long), splatter/lawnmower gardent les leurs. Non enfant d'un composite
		// (vehicle_mastery cible `splatter`, pas `road_trip`) → aucun composite impacté.
		{Norm: "road_trip", Display: "Virée sur la route", MappingType: mappingTypeMedal, MedalID: 221693153, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Road_Trip.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un Spartan ennemi avec un véhicule terrestre",
			TierTargets: "3000,6000,9000,14400,29200"},
		{Norm: "sting_like_a_bee", Display: "Pique comme une abeille", MappingType: mappingTypeStat,
			StatName: "melee_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Sting_like_a_bee.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un Spartan ennemi en combat rapproché",
			TierTargets: "5000,10000,15000,24000,48600"},
		{Norm: "the_reaper", Display: "Le faucheur", MappingType: mappingTypeMedal, MedalID: 2625820422, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_The_Reaper.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un adversaire d'outre-tombe",
			TierTargets: "500,1000,1500,2400,4850"},
		{Norm: "too_fast_for_you", Display: "Trop rapide pour toi", MappingType: mappingTypeMedal, MedalID: 2123530881, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Too_fast_for_you.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un adversaire qui vous a tiré dessus en premier",
			TierTargets: "2000,4000,6000,9600,19400"},
		{Norm: "vandalism", Display: "Vandalisme", MappingType: mappingTypeCustom,
			CustomFunction: "compute_vandalism", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Vandalism.png",
			Category:    citationCatSpartanCompanies,
			Description: "Détruire un véhicule ennemi",
			TierTargets: "1200,2400,3600,5760,11640"},

		// ── PVP — Véhicules destructeurs (7) ─────────────────────────
		{Norm: "wraith_destroyer", Display: "Destructeur d'apparitions", MappingType: mappingTypeCustom,
			CustomFunction: "compute_wraith_destroyer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_d'apparitions.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les apparitions occupées par l'adversaire.",
			TierTargets: tierTargets3_6_9_15_30, Subcategory: citationSubCovenant},
		{Norm: "banshee_destroyer", Display: "Destructeur de banshees", MappingType: mappingTypeAward,
			AwardName: "destroyed_banshee", AwardCategory: awardCategoryVehicle, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_de_banshees.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les banshees occupés par l'adversaire.",
			TierTargets: tierTargets3_6_9_15_30, Subcategory: citationSubCovenant},
		{Norm: "ghost_destroyer", Display: "Destructeur de ghosts", MappingType: mappingTypeAward,
			AwardName: "destroyed_ghost", AwardCategory: awardCategoryVehicle, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_de_ghosts.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les ghosts occupés par l'adversaire.",
			TierTargets: tierTargets5_10_15_25_50, Subcategory: citationSubCovenant},
		{Norm: "mongoose_destroyer", Display: "Destructeur de mongooses", MappingType: mappingTypeCustom,
			CustomFunction: "compute_mongoose_destroyer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_de_mongooses.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les mongooses occupées par l'adversaire.",
			TierTargets: tierTargets5_10_15_25_50, Subcategory: citationSubUNSC},
		{Norm: "scorpion_destroyer", Display: "Destructeur de scorpions", MappingType: mappingTypeAward,
			AwardName: "destroyed_scorpion", AwardCategory: awardCategoryVehicle, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_de_scorpions.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les scorpions occupés par l'adversaire.",
			TierTargets: "1,3,5,7,10", Subcategory: citationSubUNSC},
		{Norm: "warthog_destroyer", Display: "Destructeur de warthogs", MappingType: mappingTypeCustom,
			CustomFunction: "compute_warthog_destroyer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_de_warthogs.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les warthogs occupés par l'adversaire.",
			TierTargets: tierTargets5_10_15_25_50, Subcategory: citationSubUNSC},
		{Norm: "wasp_destroyer", Display: "Destructeur de wasps", MappingType: mappingTypeAward,
			AwardName: "destroyed_wasp", AwardCategory: awardCategoryVehicle, Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Destructeur_de_wasps.png",
			Category:    citationCatVehicule,
			Description: "Détruisez les wasps occupés par l'adversaire.",
			TierTargets: tierTargets3_6_9_15_30, Subcategory: citationSubUNSC},

		// ── PVE — Firefight (10, dont 4 désactivées) ──────────────────
		{Norm: "grunt_slayer", Display: "Tueur de Grognards", MappingType: mappingTypePVEStat,
			StatName: "grunt_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Tueur_de_Grognards.png",
			Category:    citationCatEnnemi,
			Description: "Tuez des Grognards.",
			TierTargets: tierTargets10_20_30_50_100, Subcategory: citationSubCovenant},
		{Norm: "elite_slayer", Display: "Tueur d'Élites", MappingType: mappingTypePVEStat,
			StatName: "elite_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Tueur_d'Élites.png",
			Category:    citationCatEnnemi,
			Description: "Tuez des Élites.",
			TierTargets: tierTargets10_20_30_50_100, Subcategory: citationSubCovenant},
		{Norm: "jackal_slayer", Display: "Tueur de Rapaces", MappingType: mappingTypePVEStat,
			StatName: "jackal_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Tueur_de_Rapaces.png",
			Category:    citationCatEnnemi,
			Description: "Tuez des Rapaces.",
			TierTargets: tierTargets5_10_15_25_50, Subcategory: citationSubCovenant},
		{Norm: "hunter_slayer", Display: "Tueur de Chasseurs", MappingType: mappingTypePVEStat,
			StatName: "hunter_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Tueur_de_Chasseurs.png",
			Category:    citationCatEnnemi,
			Description: "Tuez des Chasseurs.",
			TierTargets: "2,4,6,10,20", Subcategory: citationSubCovenant},
		{Norm: "sentinel_slayer", Display: "Tueur de sentinelles", MappingType: mappingTypePVEStat,
			StatName: "sentinel_kills", Enabled: false,
			ImagePath:   wpH5 + "H5G_citation_Tueur_de_sentinelles.png",
			Category:    citationCatEnnemi,
			Description: "Tuez des sentinelles.",
			TierTargets: tierTargets5_10_15_25_50, Subcategory: citationSubBanished},
		{Norm: "like_a_boss", Display: "Comme un Boss", MappingType: mappingTypePVEStat,
			StatName: "boss_kills", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Like_a_boss.png",
			Category:    citationCatSpartanCompanies,
			Description: "Tuer un boss dans une partie Baptême du feu zone de combat",
			TierTargets: "250,500,750,1200,2400"},
		// I7 suite (2026-07-24) — DÉCISION UTILISATEUR : « Éliminations Firefight » compte
		// les VICTOIRES en Baptême du feu (la description « Gagner des parties en Baptême du
		// feu » était déjà correcte ; l'ancien stat_name total_enemy_kills comptait des kills
		// = faux). Bascule sur la fonction custom compute_wins_firefight (déjà implémentée et
		// enregistrée dans citations_custom.go, jusqu'ici NON liée à une citation → dead code
		// résorbé) : renvoie 1 par match Firefight gagné (outcome == OutcomeWin), 0 sinon —
		// même patron que flag_victory / slayer_victory / strongholds_victory, d'où le même
		// palier de victoires tierTargets5_10_15_25_50 (recalibré depuis l'échelle kills x00).
		// Reste thématiquement Firefight (Category inchangée). Non enfant d'un composite → la
		// sémantique de covenant_destroyer et des autres composites reste inchangée.
		{Norm: "player_vs_everything", Display: "Éliminations Firefight", MappingType: mappingTypeCustom,
			CustomFunction: "compute_wins_firefight", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Player_vs_Everything.png",
			Category:    citationCatSpartanCompanies,
			Description: "Gagner des parties en Baptême du feu",
			TierTargets: tierTargets5_10_15_25_50},
		{Norm: "brute_slayer", Display: "Tueur de Brutes", MappingType: mappingTypePVEStat,
			StatName:    "brute_kills",
			Enabled:     false,
			Category:    citationCatEnnemi,
			Description: "Tuez des Brutes.",
			TierTargets: "10,20,30,50,100", Subcategory: citationSubBanished},
		{Norm: "skimmer_slayer", Display: "Tueur de Skimmers", MappingType: mappingTypePVEStat,
			StatName:    "skimmer_kills",
			Enabled:     false,
			Category:    citationCatEnnemi,
			Description: "Tuez des Skimmers.",
			TierTargets: "10,20,30,50,100", Subcategory: citationSubBanished},
		{Norm: "marine_slayer", Display: "Tueur de Marines", MappingType: mappingTypePVEStat,
			StatName: "marine_kills", Enabled: false,
			ImagePath:   wpH5 + "H5G_citation_Tueur_de_répliques_de_Marines.png",
			Category:    citationCatEnnemi,
			Description: "Tuez les Marines ennemis.",
			TierTargets: "20,40,60,100,200", Subcategory: citationSubBanished},

		// ── Armes — UNSC (10) ─────────────────────────────────────────
		{Norm: "br75_mastery", Display: "Maîtrise du BR75", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:BR75", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_BR75.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le BR75.",
			TierTargets: "25,50,100,200,500", Subcategory: citationSubUNSC},
		{Norm: "ma40_mastery", Display: "Maîtrise du MA40 AR", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:MA40 AR", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_MA40.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le MA40 AR.",
			TierTargets: "25,50,100,200,500", Subcategory: citationSubUNSC},
		{Norm: "sidekick_mastery", Display: "Maîtrise du MK50 Sidekick", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Mk51 Sidekick", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Sidekick.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le MK50 Sidekick.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubUNSC},
		{Norm: "commando_mastery", Display: "Maîtrise du VK78 Commando", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:VK78 Commando", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Commando.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le VK78 Commando.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubUNSC},
		{Norm: "sniper_mastery", Display: "Maîtrise du S7 Sniper", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:S7 Sniper", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Sniper-S7.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le S7 Sniper.",
			TierTargets: tierTargets10_20_40_80_200, Subcategory: citationSubUNSC},
		{Norm: "spnkr_mastery", Display: "Maîtrise du M41 SPNKr", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:M41 SPNKr", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_SPNKR.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le M41 SPNKr.",
			TierTargets: tierTargets10_20_40_80_200, Subcategory: citationSubUNSC},
		{Norm: "bulldog_mastery", Display: "Maîtrise du CQS48 Bulldog", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:CQS48 Bulldog", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Bulldog.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le CQS48 Bulldog.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubUNSC},
		{Norm: "bandit_mastery", Display: "Maîtrise du Bandit EVO", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Bandit Evo", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Bandit.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Bandit EVO.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubUNSC},
		{Norm: "hydra_mastery", Display: "Maîtrise du MLRS-2 Hydra", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:MLRS-2 Hydra", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Hydra.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le MLRS-2 Hydra.",
			TierTargets: "5,10,20,40,100", Subcategory: citationSubUNSC},
		{Norm: "mutilator_mastery", Display: "Maîtrise du Mutilateur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Mutilator", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Mutilator.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Mutilateur.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubUNSC},

		// ── Armes — Paria (9) ─────────────────────────────────────────
		{Norm: "stalker_mastery", Display: "Maîtrise du Fusil traqueur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Stalker Rifle", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Stalker.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Fusil traqueur.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubParia},
		{Norm: "needler_mastery", Display: "Maîtrise du Needler", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Needler", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Needler.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Needler.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubParia},
		{Norm: "energy_sword_mastery", Display: "Maîtrise de l'Épée à énergie", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Energy Sword", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Épée_à_énergie.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec l'Épée à énergie.",
			TierTargets: tierTargets10_20_40_80_200, Subcategory: citationSubParia},
		{Norm: "mangler_mastery", Display: "Maîtrise du Déchiqueteur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Mangler", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Mangler.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Déchiqueteur.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubParia},
		{Norm: "skewer_mastery", Display: "Maîtrise de l'Empaleur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Skewer", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Skewer.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec l'Empaleur.",
			TierTargets: "5,10,20,40,100", Subcategory: citationSubParia},
		{Norm: "gravity_hammer_mastery", Display: "Maîtrise du Marteau antigravité", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Gravity Hammer", Enabled: true,
			ImagePath:   wpH5 + "H5G_citation_Marteau_antigrav.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Marteau antigravité.",
			TierTargets: tierTargets10_20_40_80_200, Subcategory: citationSubParia},
		{Norm: "pulse_carbine_mastery", Display: "Maîtrise de la Carabine à impulsion", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Pulse Carbine", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Carabine.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec la Carabine à impulsion.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubParia},
		{Norm: "ravager_mastery", Display: "Maîtrise du Ravageur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Ravager", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Ravager.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Ravageur.",
			TierTargets: "5,10,20,40,100", Subcategory: citationSubParia},
		{Norm: "plasma_pistol_mastery", Display: "Maîtrise du Pistolet à plasma", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Plasma Pistol", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Plasma.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Pistolet à plasma.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubParia},

		// ── Armes — Forerunner (5) ────────────────────────────────────
		{Norm: "heatwave_mastery", Display: "Maîtrise du Calcineur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Heatwave", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Heatwave.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Calcineur.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubForerunner},
		{Norm: "cindershot_mastery", Display: "Maîtrise du Crémateur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Cindershot", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Cremator.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Crémateur.",
			TierTargets: tierTargets10_20_40_80_200, Subcategory: citationSubForerunner},
		{Norm: "sentinel_beam_mastery", Display: "Maîtrise du Rayon de Sentinelle", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Sentinel Beam", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Sentinel.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Rayon de Sentinelle.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubForerunner},
		{Norm: "disruptor_mastery", Display: "Maîtrise du Disrupteur", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Disruptor", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Disruptor.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Disrupteur.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubForerunner},
		{Norm: "shock_rifle_mastery", Display: "Maîtrise du Fusil électrique", MappingType: mappingTypeWeaponStat,
			StatName: "weapon_kills:Shock Rifle", Enabled: true,
			ImagePath:   wpHI + "HI_Commendations_Shock.png",
			Category:    citationCatArme,
			Description: "Éliminez des Spartans avec le Fusil électrique.",
			TierTargets: tierTargets10_25_50_100_250, Subcategory: citationSubForerunner},

		// ── Composites (7) ────────────────────────────────────────────
		{Norm: "covenant_destroyer", Display: "Destructeur de Covenants", MappingType: mappingTypeComposite,
			CompositeChildren: `["grunt_slayer","elite_slayer","jackal_slayer","hunter_slayer","like_a_boss","brute_slayer","skimmer_slayer"]`,
			Enabled:           true,
			ImagePath:         wpH5 + "H5G_maîtrise_Destructeur_de_Covenants.png",
			Category:          citationCatEnnemi,
			Description:       "Obtenez toutes les citations d'élimination de Covenants",
			Subcategory:       citationSubCovenant},
		{Norm: "grenade_mastery", Display: "Maîtrise des grenades", MappingType: mappingTypeComposite,
			CompositeChildren: `["frag_grenade","plasma_grenade"]`,
			Enabled:           true,
			ImagePath:         wpH5 + "H5G_Maîtrise_des_grenades.png",
			Category:          citationCatArme,
			Description:       "Obtenez toutes les citations de grenade.",
			Subcategory:       "Grenade"},
		{Norm: "vehicle_mastery", Display: "Maîtrise de véhicule", MappingType: mappingTypeComposite,
			CompositeChildren: `["splatter","driver","wraith_destroyer","banshee_destroyer","ghost_destroyer","mongoose_destroyer","scorpion_destroyer","warthog_destroyer","wasp_destroyer"]`,
			Enabled:           true,
			ImagePath:         wpH5 + "Vehicle_Mastery.png",
			Category:          citationCatVehicule,
			Description:       "Obtenez toutes les citations de véhicule.",
			Subcategory:       citationSubGeneral},
		{Norm: "human_weapons_mastery", Display: "Maîtrise des armes UNSC", MappingType: mappingTypeComposite,
			CompositeChildren: `["br75_mastery","ma40_mastery","sidekick_mastery","commando_mastery","sniper_mastery","spnkr_mastery","bulldog_mastery","bandit_mastery","hydra_mastery","mutilator_mastery"]`,
			Enabled:           true,
			ImagePath:         wpH5 + "H5G_Maîtrise_en_armes_UNSC.png",
			Category:          citationCatArme,
			Description:       "Obtenez toutes les citations de maîtrise d'armes UNSC.",
			Subcategory:       citationSubUNSC},
		{Norm: "paria_weapons_mastery", Display: "Maîtrise des armes Parias", MappingType: mappingTypeComposite,
			CompositeChildren: `["stalker_mastery","needler_mastery","energy_sword_mastery","mangler_mastery","skewer_mastery","gravity_hammer_mastery","pulse_carbine_mastery","ravager_mastery","plasma_pistol_mastery"]`,
			Enabled:           true,
			ImagePath:         wpHI + "HI_Maîtrise_en_armes_lourdes_Parias.png",
			Category:          citationCatArme,
			Description:       "Obtenez toutes les citations de maîtrise d'armes Parias.",
			Subcategory:       citationSubParia},
		{Norm: "forerunner_weapons_mastery", Display: "Maîtrise des armes Forerunner", MappingType: mappingTypeComposite,
			CompositeChildren: `["heatwave_mastery","cindershot_mastery","sentinel_beam_mastery","disruptor_mastery","shock_rifle_mastery"]`,
			Enabled:           true,
			ImagePath:         wpH5 + "H5G_Maîtrise_en_armes_lourdes_forerunners.png",
			Category:          citationCatArme,
			Description:       "Obtenez toutes les citations de maîtrise d'armes Forerunner.",
			Subcategory:       citationSubForerunner},
		{Norm: "all_weapons_mastery", Display: "Maîtrise en armement", MappingType: mappingTypeComposite,
			CompositeChildren: `["human_weapons_mastery","paria_weapons_mastery","forerunner_weapons_mastery","grenade_mastery"]`,
			Enabled:           true,
			ImagePath:         wpH5 + "H5G_Maîtrise_en_armement.png",
			Category:          citationCatArme,
			Description:       "Obtenez toutes les citations d'armement.",
			Subcategory:       citationSubGeneral},
	}
}

// citationDisplayEN — nom ANGLAIS par citation (clé = Norm). Les citations Infinite
// sont des copies de commendations Halo 5 (seul le calcul de progression diffère),
// donc l'anglais provient, par ordre de fiabilité :
//   - du name_en OFFICIEL H5 quand le nom FR correspond exactement (38) ;
//   - de « <arme> Mastery » pour les maîtrises d'armes Infinite (armes absentes de H5) ;
//   - du Norm lui-même, qui encode déjà l'anglais (grand_theft → Grand Theft, etc.).
//
// Consommé par citationDisplayENOr() au seed → colonne citation_name_display_en,
// servie locale-aware au read. Absent ⇒ fallback FR (jamais vide).
var citationDisplayEN = map[string]string{
	// ── Correspondances officielles Halo 5 (name_en) ───────────────────────────
	"assassin":            "Assassin",
	"assistant":           "Assistant",
	"banshee_destroyer":   "Banshee Destroyer",
	"bulldozer":           "Bulldozer",
	"charge":              "Storm the Walls",
	"close_combat":        "Close Quarters",
	"covenant_destroyer":  "Covenant Destroyer",
	"driver":              "Wheelman",
	"eagle_eye":           "Whites of Their Eyes",
	"elite_slayer":        "Elite Slayer",
	"flag_carrier_hunter": "Carrier Takedown",
	"flag_defender":       "Defender of the Flag",
	"flag_victory":        "Flag Victory",
	"forced_annexation":   "Aggressive Expansion",
	"frag_grenade":        "Frag Grenade",
	"ghost_destroyer":     "Ghost Destroyer",
	"grenade_mastery":     "Grenade Mastery",
	"grunt_slayer":        "Grunt Slayer",
	"headshot":            "Headshot",
	"hunter_slayer":       "Hunter Slayer",
	"jackal_slayer":       "Jackal Slayer",
	"melee_fighter":       "Smash",
	"mongoose_destroyer":  "Mongoose Destroyer",
	"multikill":           "Multikill",
	"opportunist":         "Combat Opportunist",
	"plasma_grenade":      "Plasma Grenade",
	"scorpion_destroyer":  "Scorpion Destroyer",
	"slayer_victory":      "Slayer Victory",
	"spartan_carnage":     "Spartan Spree",
	"spartan_killer":      "Spartan Slayer",
	"splatter":            "Splatter",
	"stakeholder":         "Head in the Game",
	"strongholds_victory": "Stronghold Victory",
	"vehicle_mastery":     "Vehicle Mastery",
	"warthog_destroyer":   "Warthog Destroyer",
	"wasp_destroyer":      "Wasp Destroyer",
	"wraith_destroyer":    "Wraith Destroyer",
	"all_weapons_mastery": "Weapon Mastery",
	// ── Citations d'objectif v7.2.1 (source objective_stat) ────────────────────
	// Noms EN arbitrés par l'utilisateur le 2026-07-25 ; le Norm en est la forme
	// snake_case, sauf les 4 dont le Norm reprend la colonne source (flag_captures,
	// flag_secures, flag_steals, skull_grabs).
	citationNormFlagCaptures:         "Flag Captures",
	citationNormFlagSecures:          "Flag Secures",
	citationNormFlagSteals:           "Flag Steals",
	citationNormReturnerTakedown:     "Returner Takedown",
	citationNormUnstoppableCarrier:   "Unstoppable Carrier",
	citationNormAggressiveReturn:     "Aggressive Return",
	citationNormZoneDefense:          "Zone Defense",
	citationNormUntouchableCarrier:   "Untouchable Carrier",
	citationNormSkullCarrierTakedown: "Skull Carrier Takedown",
	citationNormSkullGrabs:           "Skull Grabs",
	// ── Médailles / concepts Infinite (anglais encodé par le Norm) ─────────────
	"avenger":               "Avenger",
	"im_just_perfect":       "Perfect",
	"lawnmower":             "Lawnmower",
	"road_trip":             "Road Trip",
	"the_reaper":            "Reaper",
	"too_fast_for_you":      "Too Fast for You",
	"flag_em_down":          "Flag 'Em Down",
	"got_you":               "Got You!",
	"grand_theft":           "Grand Theft",
	"helping_hand":          "Helping Hand",
	"like_a_boss":           "Like a Boss",
	"look_ma_no_pin":        "Look Ma, No Pin!",
	"lucky":                 "Lucky",
	"no_hard_feelings":      "No Hard Feelings",
	"positive_contribution": "Positive Contribution",
	"power_play":            "Power Play",
	"sting_like_a_bee":      "Sting Like a Bee",
	"vandalism":             "Vandalism",
	"player_vs_everything":  "Player vs. Everything",
	"sentinel_slayer":       "Sentinel Slayer",
	"brute_slayer":          "Brute Slayer",
	"skimmer_slayer":        "Skimmer Slayer",
	"marine_slayer":         "Marine Slayer",
	// ── Maîtrises d'armes Infinite (« <arme EN> Mastery ») ─────────────────────
	"bandit_mastery":         "Bandit EVO Mastery",
	"br75_mastery":           "BR75 Mastery",
	"bulldog_mastery":        "CQS48 Bulldog Mastery",
	"cindershot_mastery":     "Cindershot Mastery",
	"commando_mastery":       "VK78 Commando Mastery",
	"disruptor_mastery":      "Disruptor Mastery",
	"energy_sword_mastery":   "Energy Sword Mastery",
	"gravity_hammer_mastery": "Gravity Hammer Mastery",
	"heatwave_mastery":       "Heatwave Mastery",
	"hydra_mastery":          "MLRS-2 Hydra Mastery",
	"ma40_mastery":           "MA40 AR Mastery",
	"mangler_mastery":        "Mangler Mastery",
	"mutilator_mastery":      "Mutilator Mastery",
	"needler_mastery":        "Needler Mastery",
	"plasma_pistol_mastery":  "Plasma Pistol Mastery",
	"pulse_carbine_mastery":  "Pulse Carbine Mastery",
	"ravager_mastery":        "Ravager Mastery",
	"sentinel_beam_mastery":  "Sentinel Beam Mastery",
	"shock_rifle_mastery":    "Shock Rifle Mastery",
	"sidekick_mastery":       "Mk50 Sidekick Mastery",
	"skewer_mastery":         "Skewer Mastery",
	"sniper_mastery":         "S7 Sniper Mastery",
	"spnkr_mastery":          "M41 SPNKr Mastery",
	"stalker_mastery":        "Stalker Rifle Mastery",
	// ── Composites d'armes (catégorie) ─────────────────────────────────────────
	"human_weapons_mastery":      "UNSC Weapon Mastery",
	"paria_weapons_mastery":      "Banished Weapon Mastery",
	"forerunner_weapons_mastery": "Forerunner Weapon Mastery",
}

// citationDescriptionEN — description ANGLAISE par citation (clé = Norm). Symétrique de
// citationDisplayEN. Les citations Infinite étant des copies de commendations Halo 5, la
// source EN autoritative des descriptions est, par ordre de fiabilité (GH4) :
//   - la description OFFICIELLE H5 (API Metadata www.haloapi.com /commendations, EN) pour
//     les citations qui reprennent une commendation H5 in-match (mode de jeu, multijoueur,
//     véhicules, éliminations d'ennemis, grenades) — 57 citations ;
//   - la page Halopedia des commendations Halo 5 (section Spartan Company, absente de
//     l'endpoint metadata) pour les 15 citations Spartan Companies ;
//   - une traduction fidèle du FR dans l'idiome officiel « Kill enemy Spartans with the
//     <arme> », pour les 24 maîtrises d'armes Infinite (armes absentes de H5) et les 4
//     citations Infinite-only (avenger, sentinel/brute/skimmer slayer).
//
// Consommé par citationDescriptionENOr() au seed → colonne description_en, servie
// locale-aware au read (Q26j/Q34). Absent ⇒ description_en NULL ⇒ tooltip = nom seul EN
// (fallback GH2-B2 conservé, principe GH-5b « EN n'injecte jamais de FR »).
var citationDescriptionEN = map[string]string{
	// ── Mode de jeu (source : API H5 officielle /commendations) ─────────────────
	"charge":              "Take over any base in any Stronghold gametype in matchmaking.",
	"forced_annexation":   "Take over 3 bases without dying in any Stronghold gametype in matchmaking.",
	"assistant":           "Earn any Assist medal in Warzone.",
	"bulldozer":           "Finish with a KDA over 8 in any Slayer gametype in matchmaking.",
	"flag_defender":       "Protect your team's flag in any Capture the Flag gametype in matchmaking.",
	"got_you":             "Return your team's flag in any Capture the Flag gametype in matchmaking.",
	"stakeholder":         "Defend a team base in any Stronghold gametype in matchmaking.",
	"flag_carrier_hunter": "Kill an enemy flag carrier in any Capture the Flag gametype in matchmaking.",
	"flag_victory":        "Win a match in any Capture the Flag gametype in matchmaking.",
	"slayer_victory":      "Be on the winning team of a Slayer match.",
	"strongholds_victory": "Win a match in any Stronghold gametype in matchmaking.",
	// ── Mode de jeu · objectifs v7.2.1 (idiome officiel H5 « … in any <mode>
	// gametype in matchmaking. », traduction fidèle du FR) ──────────────────────
	citationNormFlagCaptures:         "Capture the enemy flag in any Capture the Flag gametype in matchmaking.",
	citationNormFlagSecures:          "Secure your team's flag in any Capture the Flag gametype in matchmaking.",
	citationNormFlagSteals:           "Steal the enemy flag from its base in any Capture the Flag gametype in matchmaking.",
	citationNormReturnerTakedown:     "Kill enemies returning their own flag in any Capture the Flag gametype in matchmaking.",
	citationNormUnstoppableCarrier:   "Kill an enemy while carrying the flag in any Capture the Flag gametype in matchmaking.",
	citationNormAggressiveReturn:     "Kill an enemy while returning your team's flag in any Capture the Flag gametype in matchmaking.",
	citationNormZoneDefense:          "Kill an enemy inside a zone held by your team in any Stronghold gametype in matchmaking.",
	citationNormUntouchableCarrier:   "Kill an enemy while carrying the skull in any Oddball gametype in matchmaking.",
	citationNormSkullCarrierTakedown: "Kill the enemy skull carrier in any Oddball gametype in matchmaking.",
	citationNormSkullGrabs:           "Pick up the skull in any Oddball gametype in matchmaking.",
	// ── Véhicule + grenade (API H5) ─────────────────────────────────────────────
	"splatter":       "Splatter an enemy Spartan with a vehicle.",
	"driver":         "Earn Vehicle Skill medals.",
	"frag_grenade":   "Kill an enemy Spartan with the Frag Grenade.",
	"plasma_grenade": "Kill an enemy Spartan with the Plasma Grenade.",
	// ── Multijoueur (API H5) ────────────────────────────────────────────────────
	"assassin":        "Assassinate enemy Spartans.",
	"spartan_carnage": "Kill multiple enemy Spartans without dying.",
	"close_combat":    "Earn any CQC medal.",
	"opportunist":     "Earn any combat skill medal.",
	"multikill":       "Quickly kill multiple enemy Spartans.",
	"melee_fighter":   "Kill an enemy Spartan with melee.",
	"headshot":        "Kill an enemy Spartan with a headshot.",
	"spartan_killer":  "Take out enemy Spartans.",
	"eagle_eye":       "Kill a full health enemy Spartan with a precision weapon without missing any shots.",
	// ── Véhicules destructeurs (API H5) ─────────────────────────────────────────
	"wraith_destroyer":   "Destroy enemy occupied Wraiths.",
	"banshee_destroyer":  "Destroy enemy occupied Banshees.",
	"ghost_destroyer":    "Destroy enemy occupied Ghosts.",
	"mongoose_destroyer": "Destroy enemy occupied Mongooses.",
	"scorpion_destroyer": "Destroy enemy occupied Scorpions.",
	"warthog_destroyer":  "Destroy enemy occupied Warthogs.",
	"wasp_destroyer":     "Destroy enemy occupied Wasps.",
	// ── Éliminations Firefight (API H5) ─────────────────────────────────────────
	"grunt_slayer":         "Kill Grunts.",
	"elite_slayer":         "Kill Elites.",
	"jackal_slayer":        "Kill Jackals.",
	"hunter_slayer":        "Kill Hunters.",
	"marine_slayer":        "Kill enemy Marines.",
	"like_a_boss":          "Kill a boss in a Warzone Firefight match.",
	"player_vs_everything": "Win matches in Warzone Firefight.",
	// ── Spartan Company (source : Halopedia + traduction fidèle du FR) ───────────
	"flag_em_down":          "Earn any of these medals: Interception, Flag Bout, Carrier Kill, Flag Return, Flag Defense.",
	"grand_theft":           "Hijack a vehicle or aircraft.",
	"helping_hand":          "Earn any assist.",
	"im_just_perfect":       "Kill a player with a precision weapon without missing a shot.",
	"lawnmower":             "Splatter an opponent with a vehicle.",
	"look_ma_no_pin":        "Kill an enemy Spartan with any grenade.",
	"lucky":                 "Earn the Lucky, Empty Clip, Sayonara, or Cannonball medals.",
	"no_hard_feelings":      "Kill enemy Spartans.",
	"positive_contribution": "Finish with a KDA over 8 in any Slayer game in matchmaking.",
	"power_play":            "Kill an enemy Spartan with a power weapon.",
	"road_trip":             "Kill an enemy Spartan with a ground vehicle.",
	"sting_like_a_bee":      "Kill an enemy Spartan in close combat.",
	"the_reaper":            "Kill an opponent from beyond the grave.",
	"too_fast_for_you":      "Kill an opponent that shot you first.",
	"vandalism":             "Destroy an enemy vehicle.",
	// ── Maîtrises d'armes Infinite (trad fidèle, idiome officiel « Kill … with the ») ──
	"br75_mastery":           "Kill enemy Spartans with the BR75.",
	"ma40_mastery":           "Kill enemy Spartans with the MA40 AR.",
	"sidekick_mastery":       "Kill enemy Spartans with the Mk50 Sidekick.",
	"commando_mastery":       "Kill enemy Spartans with the VK78 Commando.",
	"sniper_mastery":         "Kill enemy Spartans with the S7 Sniper.",
	"spnkr_mastery":          "Kill enemy Spartans with the M41 SPNKr.",
	"bulldog_mastery":        "Kill enemy Spartans with the CQS48 Bulldog.",
	"bandit_mastery":         "Kill enemy Spartans with the Bandit EVO.",
	"hydra_mastery":          "Kill enemy Spartans with the MLRS-2 Hydra.",
	"mutilator_mastery":      "Kill enemy Spartans with the Mutilator.",
	"stalker_mastery":        "Kill enemy Spartans with the Stalker Rifle.",
	"needler_mastery":        "Kill enemy Spartans with the Needler.",
	"energy_sword_mastery":   "Kill enemy Spartans with the Energy Sword.",
	"mangler_mastery":        "Kill enemy Spartans with the Mangler.",
	"skewer_mastery":         "Kill enemy Spartans with the Skewer.",
	"gravity_hammer_mastery": "Kill enemy Spartans with the Gravity Hammer.",
	"pulse_carbine_mastery":  "Kill enemy Spartans with the Pulse Carbine.",
	"ravager_mastery":        "Kill enemy Spartans with the Ravager.",
	"plasma_pistol_mastery":  "Kill enemy Spartans with the Plasma Pistol.",
	"heatwave_mastery":       "Kill enemy Spartans with the Heatwave.",
	"cindershot_mastery":     "Kill enemy Spartans with the Cindershot.",
	"sentinel_beam_mastery":  "Kill enemy Spartans with the Sentinel Beam.",
	"disruptor_mastery":      "Kill enemy Spartans with the Disruptor.",
	"shock_rifle_mastery":    "Kill enemy Spartans with the Shock Rifle.",
	// ── Éliminations / natives Infinite-only (trad fidèle du FR) ────────────────
	"avenger":         "Kill the enemy responsible for your previous death.",
	"sentinel_slayer": "Kill Sentinels.",
	"brute_slayer":    "Kill Brutes.",
	"skimmer_slayer":  "Kill Skimmers.",
	// ── Composites (API H5 « Master all… » + trad fidèle des familles Infinite) ──
	"covenant_destroyer":         "Master all Covenant kill commendations.",
	"grenade_mastery":            "Master all grenade commendations.",
	"vehicle_mastery":            "Master all vehicle commendations.",
	"human_weapons_mastery":      "Master all UNSC weapon commendations.",
	"paria_weapons_mastery":      "Master all Banished weapon commendations.",
	"forerunner_weapons_mastery": "Master all Forerunner weapon commendations.",
	"all_weapons_mastery":        "Master all weapon commendations.",
}

// ─────────────────────────────────────────────────────────────────────────────
// medal_definitions
// ─────────────────────────────────────────────────────────────────────────────

// SeedMedalDefinitions vérifie que medal_definitions est peuplé.
// La logique complète de population vient de l'API 343i (async) — ici on injecte
// les médailles custom si la table est vide.
