package mapper

import "time"

// MatchRegistryRow mirrors a row in shared.match_registry (DuckDB v6).
// Column names follow the schema in internal/sync/schema.go. Pointer fields
// represent SQL NULL (left empty when the data is unavailable from the
// OpenSpartan payload alone — typically referential names that live in
// metadata.duckdb and are filled in by the post-import recompute).
type MatchRegistryRow struct {
	MatchID                 string
	StartTime               time.Time
	EndTime                 *time.Time
	StartTimeUTC            time.Time
	EndTimeUTC              *time.Time
	PlaylistID              *string
	PlaylistName            *string // filled by post-import recompute
	PlaylistVersionID       *string
	MapID                   *string
	MapName                 *string // filled by post-import recompute
	MapVersionID            *string
	PairID                  *string
	PairName                *string // filled by post-import recompute
	PairVersionID           *string
	GameVariantID           *string
	GameVariantName         *string // filled by post-import recompute
	GameVariantVersionID    *string
	ModeCategory            *string // filled by post-import recompute
	IsRanked                bool    // false by default; derived during recompute
	IsFirefight             bool    // false by default; derived during recompute
	DurationSeconds         int
	PlayableDurationSeconds int
	RealStartTime           *time.Time // not present in Halo API payload
	Team0Score              *int16
	Team1Score              *int16
	Team0PsScore            *int
	Team1PsScore            *int
	BackfillCompleted       int  // 1 once the import has supplied all rows
	ParticipantsLoaded      bool // true after import
	EventsLoaded            bool // true after import (HighlightEvents rows attached)
	MedalsLoaded            bool // true after import
	FirstSyncBy             string
	FirstSyncAt             time.Time
	LastUpdatedAt           time.Time
	PlayerCount             int16
	// SeasonID est l'identifiant CSR de la saison du match (ex. "CsrSeason13-1").
	// Phase 9.5 du plan pipeline CSR : lu depuis le payload OpenSpartan
	// (MatchInfo.SeasonId, déjà disponible mais non exploité historiquement)
	// au lieu de laisser NULL et compter sur la migration de backfill.
	SeasonID *string
}

// MatchParticipantRow mirrors a row in shared.match_participants. One row
// per human player per match. PK = (match_id, xuid).
type MatchParticipantRow struct {
	MatchID           string
	XUID              string
	Gamertag          *string // resolved via MapOptions.AliasResolver; nil if unknown
	TeamID            int
	Outcome           int
	Rank              int16
	Score             int
	Kills             int16
	Deaths            int16
	Assists           int16
	KDA               float64
	Accuracy          float64
	ShotsFired        int
	ShotsHit          int
	DamageDealt       float64
	DamageTaken       float64
	PersonalScore     int
	TimePlayedSeconds int
	AvgLifeSeconds    *float64

	// Filled from PlayerMatchStats.Result.StatPerformances when available,
	// nil otherwise (the mapper does not currently type StatPerformances).
	KillsExpected  *float64
	DeathsExpected *float64
	KillsStdDev    *float64
	DeathsStdDev   *float64

	TeamMMR  *float64 // from PlayerMatchStats.Result.TeamMmr
	EnemyMMR *float64 // derived during recompute, not in raw payload

	HeadshotKills    int16
	MaxKillingSpree  *int16
	GrenadeKills     int16
	MeleeKills       int16
	PowerWeaponKills int16

	// ParticipationInfo booleans (LUSR v2 — Mini-Phase 0.5).
	// Copiés depuis openspartan.PlayerStat.ParticipationInfo.
	PresentAtBeginning  bool
	PresentAtCompletion bool
	JoinedInProgress    bool
	LeftInProgress      bool
}

// MedalEarnedRow mirrors a row in shared.medals_earned. PK = (match_id, xuid,
// medal_name_id). NameID is int64 (DuckDB BIGINT) because filmshell medal IDs
// exceed int32 (observed: 3_546_244_406).
type MedalEarnedRow struct {
	MatchID     string
	XUID        string
	MedalNameID int64
	Count       int16
}

// HighlightEventRow mirrors a row in shared.highlight_events. The id column
// is auto-generated by a DuckDB sequence and is therefore not set here.
type HighlightEventRow struct {
	MatchID   string
	EventType string
	TimeMs    *int
	XUID      *string
	TypeHint  *int
	RawJSON   string
}

// XuidAliasRow mirrors a row in shared.xuid_aliases. The mapper does not
// produce these from MatchStats — they come from reading the OpenSpartan
// XuidAliases table directly (handled by PR 3's import service).
type XuidAliasRow struct {
	XUID      string
	Gamertag  string
	LastSeen  *time.Time
	Source    string
	UpdatedAt time.Time
}

// MappedMatch bundles every row family the mapper produces from a single
// ParsedMatch. Highlight events and xuid aliases come from separate tables
// in OpenSpartan and are mapped by dedicated functions; they are NOT
// included here.
type MappedMatch struct {
	Registry     MatchRegistryRow
	Participants []MatchParticipantRow
	Medals       []MedalEarnedRow
}

// MapOptions controls optional mapper behaviour shared across functions.
type MapOptions struct {
	// AliasResolver returns the gamertag for a given XUID, or "" if unknown.
	// May be nil — when nil, all gamertag fields are left as nil pointers.
	AliasResolver func(xuid string) string

	// Now is the timestamp used to populate FirstSyncAt / LastUpdatedAt /
	// UpdatedAt fields. Defaults to time.Now() when zero.
	Now time.Time

	// Source labels the provenance of the import in match_registry.
	// Defaults to "openspartan_import" when empty.
	Source string
}

func (o MapOptions) now() time.Time {
	if o.Now.IsZero() {
		return time.Now().UTC()
	}
	return o.Now
}

func (o MapOptions) source() string {
	if o.Source == "" {
		return "openspartan_import"
	}
	return o.Source
}

func (o MapOptions) resolveGamertag(xuid string) *string {
	if o.AliasResolver == nil {
		return nil
	}
	gt := o.AliasResolver(xuid)
	if gt == "" {
		return nil
	}
	return &gt
}
