[server]
port = 8501
enableStaticServing = true
enableCORS = false
enableXsrfProtection = false

[global]
showWarningOnDirectExecution = false
logLevel = "error"

[client]
toolbarMode = "viewer"

[theme]
base = "dark"
